export interface Restaurant {
  id: string;
  name_en: string;
  name_ja: string;
  area: string;
  area_display_en: string;
  area_display_ja: string;
  cuisine: string;
  cuisine_display_en: string;
  cuisine_display_ja: string;
  budget_min: number;
  budget_max: number;
  difficulty: number;
  rating: number;
  description_en: string;
  description_ja: string;
  booking_method: string;
  booking_tips_en: string;
  english_support: boolean;
  has_counter: boolean;
  has_private_room: boolean;
  tabelog_url: string;
  google_maps_url: string;
  website_url: string;
  phone: string;
  email: string;
  address_en: string;
  address_ja: string;
  lunch_available: boolean;
  dinner_available: boolean;
  tags: string[];
  is_premium: boolean;
  created_at: string;
  updated_at: string;
}

export interface GeneratedMessage {
  id: string;
  user_id: string;
  restaurant_id: string;
  restaurant_name: string;
  message_ja: string;
  message_en: string;
  reservation_date: string;
  reservation_time: string;
  party_size: number;
  special_requests: string;
  created_at: string;
}

export const AREAS = [
  "Shinjuku", "Shibuya", "Ginza", "Roppongi", "Ebisu", "Asakusa",
  "Ikebukuro", "Ueno", "Akihabara", "Shimokitazawa", "Nakameguro",
  "Azabu-Juban", "Kanda", "Omotesando", "Tsukiji", "Other",
] as const;

export const CUISINES = [
  "Sushi", "Ramen", "Yakitori", "Tempura", "Kaiseki", "Izakaya",
  "Yakiniku", "Tonkatsu", "Udon/Soba", "Curry", "Cafe", "Other",
] as const;

export const BUDGETS = [
  { label: "Under ¥3,000", min: 0, max: 3000 },
  { label: "¥3,000 - ¥5,000", min: 3000, max: 5000 },
  { label: "¥5,000 - ¥10,000", min: 5000, max: 10000 },
  { label: "¥10,000 - ¥20,000", min: 10000, max: 20000 },
  { label: "¥20,000+", min: 20000, max: 999999 },
] as const;

export const mockRestaurants: Restaurant[] = [
  {
    id: "r1",
    name_en: "Sushi Saito",
    name_ja: "鮨 さいとう",
    area: "ginza",
    area_display_en: "Ginza",
    area_display_ja: "銀座",
    cuisine: "sushi",
    cuisine_display_en: "Sushi",
    cuisine_display_ja: "寿司",
    budget_min: 20000,
    budget_max: 40000,
    difficulty: 5,
    rating: 4.9,
    description_en: "One of Tokyo's most celebrated sushi restaurants. Chef Saito's omakase is a masterclass in Edomae sushi, featuring the finest seasonal fish prepared with exquisite technique.",
    description_ja: "東京で最も評価の高い寿司店の一つ。齋藤シェフのおまかせは江戸前寿司の最高峰。",
    booking_method: "phone",
    booking_tips_en: "Extremely difficult to book. Best to have a Japanese-speaking concierge call on your behalf. Reservations open 1 month in advance.",
    english_support: false,
    has_counter: true,
    has_private_room: false,
    tabelog_url: "",
    google_maps_url: "https://maps.google.com/?q=Sushi+Saito+Ginza",
    website_url: "",
    phone: "03-3815-6626",
    email: "",
    address_en: "1F Ark Hills South Tower, 1-4-5 Roppongi, Minato-ku, Tokyo",
    address_ja: "東京都港区六本木1-4-5 アークヒルズサウスタワー1F",
    lunch_available: false,
    dinner_available: true,
    tags: ["michelin", "counter-only"],
    is_premium: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "r2",
    name_en: "Sushi Arai",
    name_ja: "鮨 あらい",
    area: "shibuya",
    area_display_en: "Shibuya",
    area_display_ja: "渋谷",
    cuisine: "sushi",
    cuisine_display_en: "Sushi",
    cuisine_display_ja: "寿司",
    budget_min: 15000,
    budget_max: 25000,
    difficulty: 4,
    rating: 4.7,
    description_en: "A rising star in Tokyo's sushi scene. Chef Arai trained under legendary masters and brings a modern touch to traditional Edomae techniques.",
    description_ja: "東京寿司界の新星。荒井シェフは伝統的な江戸前の技法に現代的なアプローチを加える。",
    booking_method: "phone",
    booking_tips_en: "Call at least 2 weeks in advance. Lunch is slightly easier to book than dinner.",
    english_support: false,
    has_counter: true,
    has_private_room: false,
    tabelog_url: "",
    google_maps_url: "https://maps.google.com/?q=Sushi+Arai+Shibuya",
    website_url: "",
    phone: "03-6427-0620",
    email: "",
    address_en: "2-4-13 Shibuya, Shibuya-ku, Tokyo",
    address_ja: "東京都渋谷区渋谷2-4-13",
    lunch_available: true,
    dinner_available: true,
    tags: ["michelin"],
    is_premium: false,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "r3",
    name_en: "Sushi Kanesaka",
    name_ja: "鮨 かねさか",
    area: "shinjuku",
    area_display_en: "Shinjuku",
    area_display_ja: "新宿",
    cuisine: "sushi",
    cuisine_display_en: "Sushi",
    cuisine_display_ja: "寿司",
    budget_min: 10000,
    budget_max: 20000,
    difficulty: 3,
    rating: 4.5,
    description_en: "An accessible yet exceptional sushi experience in the heart of Shinjuku. Known for generous portions and friendly atmosphere.",
    description_ja: "新宿の中心で楽しめる、親しみやすくも本格的な寿司体験。",
    booking_method: "email",
    booking_tips_en: "Email in English is accepted. Book 1 week in advance for weekdays, 2 weeks for weekends.",
    english_support: true,
    has_counter: true,
    has_private_room: true,
    tabelog_url: "",
    google_maps_url: "https://maps.google.com/?q=Sushi+Kanesaka+Shinjuku",
    website_url: "",
    phone: "03-3571-0603",
    email: "reserve@kanesaka.com",
    address_en: "3-17-12 Shinjuku, Shinjuku-ku, Tokyo",
    address_ja: "東京都新宿区新宿3-17-12",
    lunch_available: true,
    dinner_available: true,
    tags: ["english-friendly"],
    is_premium: false,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "r4",
    name_en: "Fuunji",
    name_ja: "風雲児",
    area: "shinjuku",
    area_display_en: "Shinjuku",
    area_display_ja: "新宿",
    cuisine: "ramen",
    cuisine_display_en: "Ramen",
    cuisine_display_ja: "ラーメン",
    budget_min: 1000,
    budget_max: 2000,
    difficulty: 2,
    rating: 4.4,
    description_en: "Famous for their rich tsukemen (dipping noodles). The thick, creamy fish-based broth is absolutely addictive. Expect a line, but it moves quickly.",
    description_ja: "濃厚なつけ麺で有名。魚介ベースの濃厚クリーミーなスープは中毒性あり。",
    booking_method: "walk-in",
    booking_tips_en: "No reservations — walk-in only. Arrive before 11am to avoid the longest lines. Average wait is 30-45 minutes at peak times.",
    english_support: true,
    has_counter: true,
    has_private_room: false,
    tabelog_url: "",
    google_maps_url: "https://maps.google.com/?q=Fuunji+Shinjuku",
    website_url: "",
    phone: "03-6413-8480",
    email: "",
    address_en: "2-14-3 Yoyogi, Shibuya-ku, Tokyo",
    address_ja: "東京都渋谷区代々木2-14-3",
    lunch_available: true,
    dinner_available: true,
    tags: ["hidden-gem", "counter-only"],
    is_premium: false,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "r5",
    name_en: "Mutekiya",
    name_ja: "無敵家",
    area: "ikebukuro",
    area_display_en: "Ikebukuro",
    area_display_ja: "池袋",
    cuisine: "ramen",
    cuisine_display_en: "Ramen",
    cuisine_display_ja: "ラーメン",
    budget_min: 800,
    budget_max: 1500,
    difficulty: 1,
    rating: 4.2,
    description_en: "A beloved Ikebukuro institution serving rich tonkotsu ramen since 1989. The original thick pork bone broth is a must-try.",
    description_ja: "1989年創業の池袋の名店。濃厚な豚骨ラーメンは必食。",
    booking_method: "walk-in",
    booking_tips_en: "Walk-in only. Open late — great for a post-drink meal. Line moves fast.",
    english_support: true,
    has_counter: true,
    has_private_room: false,
    tabelog_url: "",
    google_maps_url: "https://maps.google.com/?q=Mutekiya+Ikebukuro",
    website_url: "",
    phone: "03-3982-7656",
    email: "",
    address_en: "1-17-1 Minamiikebukuro, Toshima-ku, Tokyo",
    address_ja: "東京都豊島区南池袋1-17-1",
    lunch_available: true,
    dinner_available: true,
    tags: ["budget-friendly"],
    is_premium: false,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "r6",
    name_en: "Toriki",
    name_ja: "鳥喜",
    area: "ebisu",
    area_display_en: "Ebisu",
    area_display_ja: "恵比寿",
    cuisine: "yakitori",
    cuisine_display_en: "Yakitori",
    cuisine_display_ja: "焼き鳥",
    budget_min: 5000,
    budget_max: 8000,
    difficulty: 3,
    rating: 4.6,
    description_en: "A refined yakitori experience in Ebisu. Premium free-range chicken grilled over high-quality binchotan charcoal. The tsukune is legendary.",
    description_ja: "恵比寿の洗練された焼き鳥店。最高級備長炭で焼く地鶏。つくねは絶品。",
    booking_method: "phone",
    booking_tips_en: "Call to reserve. Counter seats are first-come, but table seats can be booked 3-5 days ahead.",
    english_support: false,
    has_counter: true,
    has_private_room: false,
    tabelog_url: "",
    google_maps_url: "https://maps.google.com/?q=Toriki+Ebisu",
    website_url: "",
    phone: "03-3442-1129",
    email: "",
    address_en: "1-7-3 Ebisuminami, Shibuya-ku, Tokyo",
    address_ja: "東京都渋谷区恵比寿南1-7-3",
    lunch_available: false,
    dinner_available: true,
    tags: ["hidden-gem"],
    is_premium: false,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "r7",
    name_en: "Birdland",
    name_ja: "バードランド",
    area: "roppongi",
    area_display_en: "Roppongi",
    area_display_ja: "六本木",
    cuisine: "yakitori",
    cuisine_display_en: "Yakitori",
    cuisine_display_ja: "焼き鳥",
    budget_min: 8000,
    budget_max: 15000,
    difficulty: 4,
    rating: 4.8,
    description_en: "Michelin-starred yakitori in the heart of Ginza. Chef Wada elevates chicken to an art form. The liver pâté and white liver are unforgettable.",
    description_ja: "銀座のミシュラン星付き焼き鳥店。和田シェフが鶏肉を芸術に昇華。",
    booking_method: "phone",
    booking_tips_en: "Very popular. Book at least 2 weeks ahead. Japanese phone call required — ask your hotel concierge.",
    english_support: false,
    has_counter: true,
    has_private_room: true,
    tabelog_url: "",
    google_maps_url: "https://maps.google.com/?q=Birdland+Roppongi",
    website_url: "",
    phone: "03-5250-1081",
    email: "",
    address_en: "4-2-15 Ginza, Chuo-ku, Tokyo",
    address_ja: "東京都中央区銀座4-2-15",
    lunch_available: false,
    dinner_available: true,
    tags: ["michelin"],
    is_premium: false,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "r8",
    name_en: "Mikawa Zezankyo",
    name_ja: "みかわ 是山居",
    area: "ginza",
    area_display_en: "Ginza",
    area_display_ja: "銀座",
    cuisine: "tempura",
    cuisine_display_en: "Tempura",
    cuisine_display_ja: "天ぷら",
    budget_min: 10000,
    budget_max: 20000,
    difficulty: 4,
    rating: 4.7,
    description_en: "Legendary tempura master Tetsuya Saotome creates the lightest, crispiest tempura you'll ever taste. Each piece is a work of art.",
    description_ja: "伝説の天ぷら職人、早乙女哲哉が作る究極の天ぷら。一つ一つが芸術品。",
    booking_method: "phone",
    booking_tips_en: "Reservations required. Call 1-2 weeks ahead. Very limited seating — only 10 counter seats.",
    english_support: false,
    has_counter: true,
    has_private_room: false,
    tabelog_url: "",
    google_maps_url: "https://maps.google.com/?q=Mikawa+Zezankyo+Ginza",
    website_url: "",
    phone: "03-3643-8383",
    email: "",
    address_en: "1-3-1 Fukuzumi, Koto-ku, Tokyo",
    address_ja: "東京都江東区福住1-3-1",
    lunch_available: true,
    dinner_available: true,
    tags: ["michelin", "counter-only"],
    is_premium: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "r9",
    name_en: "Kohaku",
    name_ja: "虎白",
    area: "azabu-juban",
    area_display_en: "Azabu-Juban",
    area_display_ja: "麻布十番",
    cuisine: "kaiseki",
    cuisine_display_en: "Kaiseki",
    cuisine_display_ja: "懐石",
    budget_min: 20000,
    budget_max: 35000,
    difficulty: 5,
    rating: 4.9,
    description_en: "Three Michelin-starred kaiseki that pushes boundaries. Chef Koji Koizumi blends classical technique with inventive twists. The seasonal courses are breathtaking.",
    description_ja: "ミシュラン三つ星の革新的な懐石。小泉瑚司シェフが伝統と革新を融合。季節のコースは圧巻。",
    booking_method: "phone",
    booking_tips_en: "Extremely difficult. Reservations open 1 month in advance. Japanese-only phone line — hotel concierge is essential.",
    english_support: false,
    has_counter: false,
    has_private_room: true,
    tabelog_url: "",
    google_maps_url: "https://maps.google.com/?q=Kohaku+Azabu+Juban",
    website_url: "",
    phone: "03-5772-1610",
    email: "",
    address_en: "3-5-4 Azabu-Juban, Minato-ku, Tokyo",
    address_ja: "東京都港区麻布十番3-5-4",
    lunch_available: false,
    dinner_available: true,
    tags: ["michelin", "premium"],
    is_premium: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "r10",
    name_en: "Shirube",
    name_ja: "しるべ",
    area: "shimokitazawa",
    area_display_en: "Shimokitazawa",
    area_display_ja: "下北沢",
    cuisine: "izakaya",
    cuisine_display_en: "Izakaya",
    cuisine_display_ja: "居酒屋",
    budget_min: 3000,
    budget_max: 5000,
    difficulty: 2,
    rating: 4.3,
    description_en: "A cozy neighborhood izakaya in the bohemian streets of Shimokitazawa. Fantastic seasonal small plates, great sake selection, and a warm, local atmosphere.",
    description_ja: "下北沢の路地裏にある温かい雰囲気の居酒屋。旬の小皿料理と日本酒のセレクションが秀逸。",
    booking_method: "phone",
    booking_tips_en: "Walk-ins welcome but booking recommended for Friday/Saturday nights. Simple Japanese phone call — or just show up early.",
    english_support: false,
    has_counter: true,
    has_private_room: false,
    tabelog_url: "",
    google_maps_url: "https://maps.google.com/?q=Shirube+Shimokitazawa",
    website_url: "",
    phone: "03-3411-2890",
    email: "",
    address_en: "2-14-7 Kitazawa, Setagaya-ku, Tokyo",
    address_ja: "東京都世田谷区北沢2-14-7",
    lunch_available: false,
    dinner_available: true,
    tags: ["hidden-gem", "local-favorite"],
    is_premium: false,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  // ===== IZAKAYA RESTAURANTS (r11-r32) =====
  {
    id: "r11",
    name_en: "Uoshin Shinjuku",
    name_ja: "魚真 新宿店",
    area: "shinjuku",
    area_display_en: "Shinjuku",
    area_display_ja: "新宿",
    cuisine: "izakaya",
    cuisine_display_en: "Izakaya",
    cuisine_display_ja: "居酒屋",
    budget_min: 3000,
    budget_max: 5000,
    difficulty: 1,
    rating: 4.2,
    description_en: "A beloved seafood izakaya steps from Shinjuku Station, famous for its incredible 1,000-yen sashimi platter. Fresh fish is sourced daily, and the lively atmosphere with counter and table seating makes it perfect for solo travelers or small groups.",
    description_ja: "新宿駅から徒歩1分の人気海鮮居酒屋。1,000円の刺身盛り合わせが名物。毎日仕入れる新鮮な魚介が自慢。",
    booking_method: "walk-in",
    booking_tips_en: "Walk-ins welcome. Arrive before 6pm to avoid long waits on weekends. Counter seats fill up first.",
    english_support: false,
    has_counter: true,
    has_private_room: false,
    tabelog_url: "https://tabelog.com/en/tokyo/A1304/A130401/13115198/",
    google_maps_url: "https://maps.google.com/?q=魚真+新宿店",
    website_url: "https://uoshins.com/shinjuku/",
    phone: "03-3351-3772",
    email: "",
    address_en: "2F, 3-35-5 Shinjuku, Shinjuku-ku, Tokyo",
    address_ja: "東京都新宿区新宿3-35-5 2F",
    lunch_available: false,
    dinner_available: true,
    tags: ["traditional", "sake-selection", "english-menu"],
    is_premium: false,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "r12",
    name_en: "Motsuyaki Ucchan",
    name_ja: "もつ焼き うっちゃん",
    area: "shinjuku",
    area_display_en: "Shinjuku",
    area_display_ja: "新宿",
    cuisine: "izakaya",
    cuisine_display_en: "Izakaya",
    cuisine_display_ja: "居酒屋",
    budget_min: 2000,
    budget_max: 3500,
    difficulty: 2,
    rating: 4.4,
    description_en: "One of the most popular spots in Shinjuku's legendary Omoide Yokocho (Memory Lane). This tiny counter-only izakaya specializes in grilled offal skewers using the freshest ingredients. Skewers often sell out early, so come before 7pm.",
    description_ja: "新宿思い出横丁の人気店。新鮮なもつを使った絶品もつ焼きが名物。売り切れ次第閉店のため早めの来店がおすすめ。",
    booking_method: "walk-in",
    booking_tips_en: "No reservations accepted. Cash only. Arrive early as they close once skewers sell out. The tiny entrance is in Omoide Yokocho alley.",
    english_support: false,
    has_counter: true,
    has_private_room: false,
    tabelog_url: "https://tabelog.com/en/tokyo/A1304/A130401/13059673/",
    google_maps_url: "https://maps.google.com/?q=もつ焼きうっちゃん+思い出横丁",
    website_url: "",
    phone: "03-5909-5890",
    email: "",
    address_en: "Honami Bldg, 1-2-7 Nishi-Shinjuku, Shinjuku-ku, Tokyo",
    address_ja: "東京都新宿区西新宿1-2-7 穂波ビル",
    lunch_available: false,
    dinner_available: true,
    tags: ["traditional", "yokocho", "late-night", "hidden-gem"],
    is_premium: false,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "r13",
    name_en: "Shokkan Shibuya",
    name_ja: "食幹 渋谷",
    area: "shibuya",
    area_display_en: "Shibuya",
    area_display_ja: "渋谷",
    cuisine: "izakaya",
    cuisine_display_en: "Izakaya",
    cuisine_display_ja: "居酒屋",
    budget_min: 5000,
    budget_max: 8000,
    difficulty: 3,
    rating: 4.5,
    description_en: "A sophisticated modern izakaya hidden in a basement near Shibuya Station. The open kitchen showcases inventive takes on Japanese pub classics, like tempura-fried shiba ebi prawns and yuzu miso chicken. Reservations strongly recommended.",
    description_ja: "渋谷駅近くの地下に佇むモダン居酒屋。オープンキッチンから繰り出す創作和食が評判。予約推奨。",
    booking_method: "phone",
    booking_tips_en: "Reservations recommended, especially weekends. Call a few days in advance. Some English spoken by staff.",
    english_support: true,
    has_counter: true,
    has_private_room: true,
    tabelog_url: "https://tabelog.com/en/tokyo/A1303/A130301/13040639/",
    google_maps_url: "https://maps.google.com/?q=食幹+渋谷",
    website_url: "https://discovery-t.com/shokkan-shibuya/",
    phone: "03-3797-1911",
    email: "",
    address_en: "B1F HAKKA Bldg, 3-5-5 Shibuya, Shibuya-ku, Tokyo",
    address_ja: "東京都渋谷区渋谷3-5-5 HAKKAビルB1F",
    lunch_available: false,
    dinner_available: true,
    tags: ["modern", "date-spot", "hidden-gem"],
    is_premium: false,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "r14",
    name_en: "Ginza Shimada",
    name_ja: "銀座しまだ",
    area: "ginza",
    area_display_en: "Ginza",
    area_display_ja: "銀座",
    cuisine: "izakaya",
    cuisine_display_en: "Izakaya",
    cuisine_display_ja: "居酒屋",
    budget_min: 3000,
    budget_max: 5000,
    difficulty: 2,
    rating: 4.6,
    description_en: "A standing-only izakaya hidden in Ginza's backstreets, run by a chef who trained at a 3-Michelin-star kaiseki restaurant. Despite the casual standing format, the cooking is exceptionally refined and prices remain surprisingly affordable.",
    description_ja: "銀座の裏路地にある立ち飲み居酒屋。三ツ星懐石出身の店主が手がける本格料理をカジュアルに楽しめる。",
    booking_method: "walk-in",
    booking_tips_en: "No reservations. Standing only with about 10 spots. Arrive right at opening (5pm) for best chances. Cash preferred.",
    english_support: false,
    has_counter: true,
    has_private_room: false,
    tabelog_url: "https://tabelog.com/en/tokyo/A1301/A130101/13136359/",
    google_maps_url: "https://maps.google.com/?q=銀座しまだ",
    website_url: "",
    phone: "03-3572-8972",
    email: "",
    address_en: "1F Kousaka Bldg, 8-2-8 Ginza, Chuo-ku, Tokyo",
    address_ja: "東京都中央区銀座8-2-8 高坂ビル1F",
    lunch_available: false,
    dinner_available: true,
    tags: ["standing-bar", "hidden-gem", "sake-selection"],
    is_premium: false,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "r15",
    name_en: "Chanpuru-ya",
    name_ja: "ちゃんぷるーや",
    area: "ginza",
    area_display_en: "Ginza",
    area_display_ja: "銀座",
    cuisine: "izakaya",
    cuisine_display_en: "Izakaya",
    cuisine_display_ja: "居酒屋",
    budget_min: 3000,
    budget_max: 5000,
    difficulty: 1,
    rating: 4.1,
    description_en: "An underground Okinawan izakaya in Ginza serving hearty, homestyle dishes from Japan's southern islands. Try the goya champuru, rafute pork belly, and awamori spirits for a taste of Okinawa without leaving Tokyo.",
    description_ja: "銀座の地下にある沖縄料理居酒屋。ゴーヤチャンプルーやラフテーなど本格的な沖縄の家庭料理が楽しめる。",
    booking_method: "phone",
    booking_tips_en: "Walk-ins usually fine on weekdays. Phone reservations for weekend evenings. Friendly and welcoming atmosphere.",
    english_support: false,
    has_counter: true,
    has_private_room: false,
    tabelog_url: "https://tabelog.com/en/tokyo/A1301/A130101/13009489/",
    google_maps_url: "https://maps.google.com/?q=ちゃんぷるーや+銀座",
    website_url: "",
    phone: "03-3574-9191",
    email: "",
    address_en: "B1F, 6-3-5 Ginza, Chuo-ku, Tokyo",
    address_ja: "東京都中央区銀座6-3-5 B1F",
    lunch_available: false,
    dinner_available: true,
    tags: ["traditional", "hidden-gem", "late-night"],
    is_premium: false,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "r16",
    name_en: "Jomon Roppongi",
    name_ja: "ジョウモン 六本木店",
    area: "roppongi",
    area_display_en: "Roppongi",
    area_display_ja: "六本木",
    cuisine: "izakaya",
    cuisine_display_en: "Izakaya",
    cuisine_display_ja: "居酒屋",
    budget_min: 3000,
    budget_max: 5000,
    difficulty: 2,
    rating: 4.3,
    description_en: "A beloved Hakata-style kushiyaki izakaya on Roppongi's Imo Arai Zaka slope, known for its umami-packed grilled skewers. The rustic interior with a large wooden door feels warm and inviting. Popular with both locals and international visitors.",
    description_ja: "六本木芋洗い坂にある博多串焼き専門店。こだわりの炭火焼き串が人気。木の大扉が目印。",
    booking_method: "online",
    booking_tips_en: "Book via TableCheck or phone. Walk-ins possible but expect a wait on weekends. English menu available.",
    english_support: true,
    has_counter: true,
    has_private_room: true,
    tabelog_url: "https://tabelog.com/en/tokyo/A1307/A130701/13050949/",
    google_maps_url: "https://maps.google.com/?q=ジョウモン+六本木",
    website_url: "https://teyandei.com/?page_id=18",
    phone: "03-3405-2585",
    email: "",
    address_en: "1F Fujimori Bldg, 5-9-17 Roppongi, Minato-ku, Tokyo",
    address_ja: "東京都港区六本木5-9-17 藤森ビル1F",
    lunch_available: false,
    dinner_available: true,
    tags: ["traditional", "english-menu", "late-night"],
    is_premium: false,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "r17",
    name_en: "Sakana Bar Ippo",
    name_ja: "魚バル IPPO 恵比寿店",
    area: "ebisu",
    area_display_en: "Ebisu",
    area_display_ja: "恵比寿",
    cuisine: "izakaya",
    cuisine_display_en: "Izakaya",
    cuisine_display_ja: "居酒屋",
    budget_min: 3000,
    budget_max: 5000,
    difficulty: 2,
    rating: 4.4,
    description_en: "An intimate fish-and-sake bar tucked up a narrow staircase in Ebisu. The friendly staff guide you through 30-40 varieties of sake while you enjoy fresh sashimi, fluffy fish cakes, and namero (minced horse mackerel). A local favorite with a loyal crowd.",
    description_ja: "恵比寿の隠れ家的な魚とお酒のバル。30〜40種の日本酒と新鮮な刺身が楽しめる。常連に愛される名店。",
    booking_method: "phone",
    booking_tips_en: "Reservations recommended for dinner. Small space fills up quickly. The entrance is up a narrow staircase — easy to miss.",
    english_support: false,
    has_counter: true,
    has_private_room: false,
    tabelog_url: "https://tabelog.com/en/tokyo/A1303/A130302/13032678/",
    google_maps_url: "https://maps.google.com/?q=魚バルIPPO+恵比寿",
    website_url: "",
    phone: "03-3445-8418",
    email: "",
    address_en: "2F, 1-22-10 Ebisu, Shibuya-ku, Tokyo",
    address_ja: "東京都渋谷区恵比寿1-22-10 2F",
    lunch_available: false,
    dinner_available: true,
    tags: ["sake-selection", "hidden-gem", "traditional"],
    is_premium: false,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "r18",
    name_en: "Izakaya Koji",
    name_ja: "居酒屋 浩司",
    area: "asakusa",
    area_display_en: "Asakusa",
    area_display_ja: "浅草",
    cuisine: "izakaya",
    cuisine_display_en: "Izakaya",
    cuisine_display_ja: "居酒屋",
    budget_min: 2000,
    budget_max: 4000,
    difficulty: 1,
    rating: 4.2,
    description_en: "A welcoming izakaya on Asakusa's famous Hoppy Street with both indoor and outdoor seating. Known for slow-cooked beef tendon stew, deep-fried ham cutlets, and garlic gizzards. English menu available — a great first izakaya experience for visitors.",
    description_ja: "浅草ホッピー通りにある居心地の良い居酒屋。牛すじ煮込みや手作りハムカツが人気。英語メニューあり。",
    booking_method: "walk-in",
    booking_tips_en: "Walk-ins welcome. Open from 3pm on weekdays, 9am on weekends. Outdoor terrace seats are first-come-first-served.",
    english_support: true,
    has_counter: true,
    has_private_room: false,
    tabelog_url: "",
    google_maps_url: "https://maps.google.com/?q=居酒屋浩司+浅草+ホッピー通り",
    website_url: "",
    phone: "03-3841-1080",
    email: "",
    address_en: "2-3-19 Asakusa, Taito-ku, Tokyo",
    address_ja: "東京都台東区浅草2-3-19",
    lunch_available: true,
    dinner_available: true,
    tags: ["traditional", "english-menu", "yokocho"],
    is_premium: false,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "r19",
    name_en: "Otafuku",
    name_ja: "大多福",
    area: "asakusa",
    area_display_en: "Asakusa",
    area_display_ja: "浅草",
    cuisine: "izakaya",
    cuisine_display_en: "Izakaya",
    cuisine_display_ja: "居酒屋",
    budget_min: 3000,
    budget_max: 5000,
    difficulty: 2,
    rating: 4.5,
    description_en: "A century-old oden restaurant founded in 1915, serving ingredients simmered in a deeply flavored dashi broth passed down through generations. The traditional Japanese interior transports you to old-world Tokyo. A must-visit for oden lovers.",
    description_ja: "1915年創業の老舗おでん屋。代々受け継がれる出汁で煮込むおでんは格別。下町情緒あふれる店内。",
    booking_method: "phone",
    booking_tips_en: "Phone reservations recommended for dinner, especially weekends. Lunch walk-ins usually fine. A truly historic dining experience.",
    english_support: false,
    has_counter: true,
    has_private_room: true,
    tabelog_url: "https://tabelog.com/en/tokyo/A1311/A131102/13003741/",
    google_maps_url: "https://maps.google.com/?q=大多福+浅草",
    website_url: "https://otafuku.ne.jp/",
    phone: "03-3871-2521",
    email: "",
    address_en: "1-6-2 Senzoku, Taito-ku, Tokyo",
    address_ja: "東京都台東区千束1-6-2",
    lunch_available: true,
    dinner_available: true,
    tags: ["traditional", "hidden-gem", "date-spot"],
    is_premium: false,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "r20",
    name_en: "Sumibi Yakitori Odori",
    name_ja: "炭火焼鳥 おどり",
    area: "ikebukuro",
    area_display_en: "Ikebukuro",
    area_display_ja: "池袋",
    cuisine: "izakaya",
    cuisine_display_en: "Izakaya",
    cuisine_display_ja: "居酒屋",
    budget_min: 3000,
    budget_max: 5000,
    difficulty: 1,
    rating: 4.3,
    description_en: "A cozy basement yakitori izakaya near Ikebukuro Station specializing in premium Daisen chicken from Tottori Prefecture, grilled one skewer at a time over Kishu binchotan charcoal. The intimate atmosphere and skilled grilling make this a standout.",
    description_ja: "池袋駅西口徒歩3分の炭火焼鳥店。鳥取県産大山鶏を紀州備長炭で丁寧に焼き上げる。",
    booking_method: "phone",
    booking_tips_en: "Phone reservations recommended. Small basement space with counter and table seats. 3-minute walk from Ikebukuro Station west exit.",
    english_support: false,
    has_counter: true,
    has_private_room: false,
    tabelog_url: "",
    google_maps_url: "https://maps.google.com/?q=炭火焼鳥おどり+池袋",
    website_url: "",
    phone: "03-3985-4129",
    email: "",
    address_en: "B1F Daichiya Bldg, 3-29-12 Nishi-Ikebukuro, Toshima-ku, Tokyo",
    address_ja: "東京都豊島区西池袋3-29-12 大地屋ビルB1F",
    lunch_available: false,
    dinner_available: true,
    tags: ["traditional", "hidden-gem"],
    is_premium: false,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "r21",
    name_en: "Daitoryo",
    name_ja: "大統領",
    area: "ueno",
    area_display_en: "Ueno",
    area_display_ja: "上野",
    cuisine: "izakaya",
    cuisine_display_en: "Izakaya",
    cuisine_display_ja: "居酒屋",
    budget_min: 2000,
    budget_max: 3500,
    difficulty: 1,
    rating: 4.3,
    description_en: "A legendary Ameyoko izakaya established in 1950, famous for its signature horse meat stew simmered in miso. Open from morning to midnight daily, this bustling spot captures the raw energy of Ueno's market street. A must for adventurous eaters.",
    description_ja: "1950年創業のアメ横の老舗居酒屋。名物の馬もつ煮込みは創業以来の味。朝から深夜まで営業。",
    booking_method: "walk-in",
    booking_tips_en: "No reservations. Open 10am-midnight daily. Just walk in — there's always turnover. Cash only. Very lively and loud atmosphere.",
    english_support: false,
    has_counter: true,
    has_private_room: false,
    tabelog_url: "https://tabelog.com/en/tokyo/A1311/A131101/13016740/",
    google_maps_url: "https://maps.google.com/?q=大統領+上野+アメ横",
    website_url: "",
    phone: "03-3832-5622",
    email: "",
    address_en: "6-10-14 Ueno, Taito-ku, Tokyo",
    address_ja: "東京都台東区上野6-10-14",
    lunch_available: true,
    dinner_available: true,
    tags: ["traditional", "yokocho", "late-night"],
    is_premium: false,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "r22",
    name_en: "PUSHUP Akihabara",
    name_ja: "世界一周旅ダイニング居酒屋 PUSHUP 秋葉原駅店",
    area: "akihabara",
    area_display_en: "Akihabara",
    area_display_ja: "秋葉原",
    cuisine: "izakaya",
    cuisine_display_en: "Izakaya",
    cuisine_display_ja: "居酒屋",
    budget_min: 3000,
    budget_max: 5000,
    difficulty: 1,
    rating: 4.0,
    description_en: "A unique world-travel-themed izakaya run by an owner who has visited 60 countries. Enjoy 40 international craft beers alongside creative fusion dishes inspired by global flavors, all in a cozy space with warm wooden decor and soft lighting.",
    description_ja: "60カ国を旅したオーナーが営む世界一周旅ダイニング。40種の海外ビールと各国の味を取り入れた創作料理が楽しめる。",
    booking_method: "phone",
    booking_tips_en: "Reservations recommended. Great for groups. The travel-themed atmosphere makes for fun conversation. Near Akihabara Station.",
    english_support: true,
    has_counter: true,
    has_private_room: false,
    tabelog_url: "https://tabelog.com/en/tokyo/A1310/A131001/13050727/",
    google_maps_url: "https://maps.google.com/?q=PUSHUP+秋葉原",
    website_url: "",
    phone: "080-3934-3640",
    email: "",
    address_en: "2F Yorimoto Bldg, 1-5 Akihabara, Taito-ku, Tokyo",
    address_ja: "東京都台東区秋葉原1-5 頼本ビル2F",
    lunch_available: true,
    dinner_available: true,
    tags: ["modern", "craft-beer", "english-menu"],
    is_premium: false,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "r23",
    name_en: "Katsu Shimokitazawa",
    name_ja: "克ッ 下北沢",
    area: "shimokitazawa",
    area_display_en: "Shimokitazawa",
    area_display_ja: "下北沢",
    cuisine: "izakaya",
    cuisine_display_en: "Izakaya",
    cuisine_display_ja: "居酒屋",
    budget_min: 3000,
    budget_max: 5000,
    difficulty: 1,
    rating: 4.3,
    description_en: "A charming yakitori izakaya in Shimokitazawa's bohemian streets, using premium brand chickens from Tottori and Miyazaki prefectures grilled over Kishu binchotan. Their white chicken liver, served nearly rare, is a signature must-try.",
    description_ja: "下北沢の焼鳥居酒屋。鳥取県産大山どりや宮崎県産日向鶏を紀州備長炭で焼き上げる。白レバーが絶品。",
    booking_method: "phone",
    booking_tips_en: "Walk-ins welcome but it gets busy. Opens at 3pm. Counter seats great for solo diners. 4-minute walk from Shimokitazawa Station.",
    english_support: false,
    has_counter: true,
    has_private_room: false,
    tabelog_url: "https://tabelog.com/en/tokyo/A1318/A131802/13113249/",
    google_maps_url: "https://maps.google.com/?q=克ッ+下北沢",
    website_url: "https://katsu-shimokitazawa.com/",
    phone: "03-3468-3334",
    email: "",
    address_en: "1F Daiichi Katayanagi Bldg, 2-33-3 Kitazawa, Setagaya-ku, Tokyo",
    address_ja: "東京都世田谷区北沢2-33-3 第一片柳ビル1F",
    lunch_available: true,
    dinner_available: true,
    tags: ["traditional", "hidden-gem"],
    is_premium: false,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "r24",
    name_en: "Nakame no Teppen",
    name_ja: "中目のてっぺん 本店",
    area: "nakameguro",
    area_display_en: "Nakameguro",
    area_display_ja: "中目黒",
    cuisine: "izakaya",
    cuisine_display_en: "Izakaya",
    cuisine_display_ja: "居酒屋",
    budget_min: 3000,
    budget_max: 5000,
    difficulty: 2,
    rating: 4.4,
    description_en: "A hidden robatayaki izakaya just 1 minute from Nakameguro Station with a tiny, half-height entrance you have to crouch through. Inside, enjoy seasonal fresh fish and robatayaki grilled at the counter. Open until 5am, perfect for late-night dining.",
    description_ja: "中目黒駅から徒歩1分の隠れ家ろばた焼き居酒屋。小さな入口をくぐると広がる本格的な空間。朝5時まで営業。",
    booking_method: "phone",
    booking_tips_en: "Reservations recommended on weekends. Look for the tiny half-height door — no English sign outside. Late-night friendly until 5am.",
    english_support: false,
    has_counter: true,
    has_private_room: true,
    tabelog_url: "https://tabelog.com/en/tokyo/A1317/A131701/13031351/",
    google_maps_url: "https://maps.google.com/?q=中目のてっぺん+本店",
    website_url: "",
    phone: "03-5722-3902",
    email: "",
    address_en: "1F Plage Meguro, 3-9-5 Kamimeguro, Meguro-ku, Tokyo",
    address_ja: "東京都目黒区上目黒3-9-5 プラージュ・メグロ1F",
    lunch_available: false,
    dinner_available: true,
    tags: ["hidden-gem", "late-night", "sake-selection"],
    is_premium: false,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "r25",
    name_en: "Abe-chan",
    name_ja: "あべちゃん 麻布十番店",
    area: "azabu_juban",
    area_display_en: "Azabu-Juban",
    area_display_ja: "麻布十番",
    cuisine: "izakaya",
    cuisine_display_en: "Izakaya",
    cuisine_display_ja: "居酒屋",
    budget_min: 2000,
    budget_max: 4000,
    difficulty: 1,
    rating: 4.2,
    description_en: "A legendary yakiton izakaya established in 1933, famous for its grilled pork skewers basted in a tare sauce that has been continuously topped off for over 90 years. The no-frills atmosphere and cheap prices make it a true old-Tokyo gem.",
    description_ja: "1933年創業の老舗やきとん居酒屋。90年以上継ぎ足し続けた秘伝のタレが自慢。下町の味を麻布十番で。",
    booking_method: "walk-in",
    booking_tips_en: "Walk-ins only. Opens at 3pm. Closed Sundays. Cash only. Very casual — just grab a seat at the counter or tiny tables.",
    english_support: false,
    has_counter: true,
    has_private_room: false,
    tabelog_url: "https://tabelog.com/en/tokyo/A1307/A130702/13007199/",
    google_maps_url: "https://maps.google.com/?q=あべちゃん+麻布十番",
    website_url: "",
    phone: "03-3451-1518",
    email: "",
    address_en: "2-1-1 Azabu-Juban, Minato-ku, Tokyo",
    address_ja: "東京都港区麻布十番2-1-1",
    lunch_available: true,
    dinner_available: true,
    tags: ["traditional", "hidden-gem", "standing-bar"],
    is_premium: false,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "r26",
    name_en: "Kanda Kohju",
    name_ja: "かんだ光壽",
    area: "kanda",
    area_display_en: "Kanda",
    area_display_ja: "神田",
    cuisine: "izakaya",
    cuisine_display_en: "Izakaya",
    cuisine_display_ja: "居酒屋",
    budget_min: 4000,
    budget_max: 6000,
    difficulty: 2,
    rating: 4.4,
    description_en: "A refined sake-focused izakaya near Kanda Station, known for its exceptional selection of rare nihonshu and an elegant assorted appetizer plate. The upmarket approach to izakaya cuisine elevates classic dishes with seasonal ingredients.",
    description_ja: "神田駅近くの日本酒にこだわる居酒屋。希少な銘柄が揃い、季節の前菜盛り合わせが名物。上質な和の空間。",
    booking_method: "online",
    booking_tips_en: "Online reservations via website recommended. 2-minute walk from Kanda Station east exit. Popular with sake enthusiasts.",
    english_support: false,
    has_counter: true,
    has_private_room: true,
    tabelog_url: "https://tabelog.com/en/tokyo/A1310/A131002/13011272/",
    google_maps_url: "https://maps.google.com/?q=かんだ光壽",
    website_url: "http://kohju.net/",
    phone: "03-3253-0044",
    email: "",
    address_en: "Ohnuki Bldg, 2-9-7 Kajimachi, Chiyoda-ku, Tokyo",
    address_ja: "東京都千代田区鍛冶町2-9-7 大貫ビル",
    lunch_available: false,
    dinner_available: true,
    tags: ["sake-selection", "modern", "date-spot"],
    is_premium: false,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "r27",
    name_en: "Yakitori Imai",
    name_ja: "焼鳥 今井",
    area: "omotesando",
    area_display_en: "Omotesando",
    area_display_ja: "表参道",
    cuisine: "izakaya",
    cuisine_display_en: "Izakaya",
    cuisine_display_ja: "居酒屋",
    budget_min: 4000,
    budget_max: 6000,
    difficulty: 3,
    rating: 4.6,
    description_en: "A chic 30-seat yakitori izakaya in the quiet Aoyama backstreets near Omotesando. Refined skewers made with high-quality ingredients are paired with an excellent wine and sake selection. Reservations essential for this popular spot.",
    description_ja: "表参道・青山エリアの洗練された焼鳥居酒屋。厳選素材の串焼きとワイン・日本酒のペアリングが評判。要予約。",
    booking_method: "phone",
    booking_tips_en: "Reservations essential — book at least 1 week ahead. 6-minute walk from Gaiemmae Station. Upscale but casual atmosphere.",
    english_support: true,
    has_counter: true,
    has_private_room: false,
    tabelog_url: "https://tabelog.com/en/tokyo/A1306/A130603/13025995/",
    google_maps_url: "https://maps.google.com/?q=焼鳥今井+青山",
    website_url: "",
    phone: "03-6447-1710",
    email: "",
    address_en: "1F Rosa Bianca, 3-42-11 Jingumae, Shibuya-ku, Tokyo",
    address_ja: "東京都渋谷区神宮前3-42-11 ローザビアンカ1F",
    lunch_available: false,
    dinner_available: true,
    tags: ["modern", "date-spot", "sake-selection"],
    is_premium: false,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "r28",
    name_en: "Juban Shuraba",
    name_ja: "十番 修羅場",
    area: "azabu_juban",
    area_display_en: "Azabu-Juban",
    area_display_ja: "麻布十番",
    cuisine: "izakaya",
    cuisine_display_en: "Izakaya",
    cuisine_display_ja: "居酒屋",
    budget_min: 3000,
    budget_max: 5000,
    difficulty: 1,
    rating: 4.1,
    description_en: "A spacious teppanyaki-style izakaya in Azabu-Juban featuring fresh oysters and seafood sourced directly from Toyosu Market. The casual Japanese-style interior seats 52, making it great for groups. English-speaking staff available.",
    description_ja: "麻布十番の鉄板焼き居酒屋。豊洲市場直送の新鮮な牡蠣と海鮮が自慢。52席の広々とした空間。英語対応可。",
    booking_method: "phone",
    booking_tips_en: "Walk-ins welcome on weekdays. Reservations for groups recommended. Open Tuesday-Sunday from 4pm. English-speaking staff on site.",
    english_support: true,
    has_counter: true,
    has_private_room: true,
    tabelog_url: "https://tabelog.com/en/tokyo/A1307/A130702/13298869/",
    google_maps_url: "https://maps.google.com/?q=十番修羅場+麻布十番",
    website_url: "",
    phone: "03-6277-7410",
    email: "",
    address_en: "2-8-10 Azabu-Juban, Minato-ku, Tokyo",
    address_ja: "東京都港区麻布十番2-8-10",
    lunch_available: false,
    dinner_available: true,
    tags: ["modern", "english-menu", "date-spot"],
    is_premium: false,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "r29",
    name_en: "Toriya Kou",
    name_ja: "鳥やKOU",
    area: "roppongi",
    area_display_en: "Roppongi",
    area_display_ja: "六本木",
    cuisine: "izakaya",
    cuisine_display_en: "Izakaya",
    cuisine_display_ja: "居酒屋",
    budget_min: 3000,
    budget_max: 5000,
    difficulty: 3,
    rating: 4.5,
    description_en: "A Michelin Bib Gourmand yakitori izakaya in Roppongi using premium Hinai Jidori chicken from Akita Prefecture. Each skewer is carefully grilled over binchotan charcoal. The intimate counter seating lets you watch the master at work. Book ahead.",
    description_ja: "六本木のミシュラン・ビブグルマン獲得焼鳥店。秋田県産比内地鶏を備長炭で丁寧に焼き上げる。カウンター席が人気。",
    booking_method: "phone",
    booking_tips_en: "Reservations essential — this Bib Gourmand spot books up fast. Call at least 3-4 days ahead. Counter seats recommended.",
    english_support: false,
    has_counter: true,
    has_private_room: false,
    tabelog_url: "",
    google_maps_url: "https://maps.google.com/?q=鳥やKOU+六本木",
    website_url: "",
    phone: "03-5411-2911",
    email: "",
    address_en: "1F, 3-10-9 Roppongi, Minato-ku, Tokyo",
    address_ja: "東京都港区六本木3-10-9 1F",
    lunch_available: false,
    dinner_available: true,
    tags: ["traditional", "hidden-gem"],
    is_premium: false,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "r30",
    name_en: "Enza Ikebukuro",
    name_ja: "えんざ 池袋",
    area: "ikebukuro",
    area_display_en: "Ikebukuro",
    area_display_ja: "池袋",
    cuisine: "izakaya",
    cuisine_display_en: "Izakaya",
    cuisine_display_ja: "居酒屋",
    budget_min: 2500,
    budget_max: 4000,
    difficulty: 1,
    rating: 4.0,
    description_en: "A friendly neighborhood izakaya near Ikebukuro Station serving classic comfort food: motsu nikomi (offal stew), charcoal-grilled yakitori, and fresh seasonal fish. The daily-changing menu keeps regulars coming back. Great value for money.",
    description_ja: "池袋駅近くの居酒屋。もつ煮込みや炭火焼き鳥、季節の鮮魚が人気。日替わりメニューが豊富でコスパ抜群。",
    booking_method: "phone",
    booking_tips_en: "Walk-ins welcome most days. Phone reservation for groups of 4+. Casual and beginner-friendly atmosphere.",
    english_support: false,
    has_counter: true,
    has_private_room: false,
    tabelog_url: "",
    google_maps_url: "https://maps.google.com/?q=えんざ+池袋",
    website_url: "",
    phone: "03-3987-0044",
    email: "",
    address_en: "1-17-3 Minami-Ikebukuro, Toshima-ku, Tokyo",
    address_ja: "東京都豊島区南池袋1-17-3",
    lunch_available: false,
    dinner_available: true,
    tags: ["traditional", "late-night"],
    is_premium: false,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "r31",
    name_en: "Fukunoya",
    name_ja: "福の家",
    area: "akihabara",
    area_display_en: "Akihabara",
    area_display_ja: "秋葉原",
    cuisine: "izakaya",
    cuisine_display_en: "Izakaya",
    cuisine_display_ja: "居酒屋",
    budget_min: 3000,
    budget_max: 5000,
    difficulty: 1,
    rating: 4.1,
    description_en: "A welcoming izakaya near Ochanomizu Station serving regional Japanese dishes with seasonal ingredients. Private rooms available for groups, making it ideal for a relaxed dinner after exploring Akihabara. Hearty portions and reasonable prices.",
    description_ja: "御茶ノ水駅近くの居酒屋。全国各地の旬の食材を使った料理が楽しめる。個室あり。秋葉原散策後のディナーに最適。",
    booking_method: "phone",
    booking_tips_en: "Phone reservations recommended for private rooms. Walk-ins fine for counter seats. Near Ochanomizu Station, short walk from Akihabara.",
    english_support: false,
    has_counter: true,
    has_private_room: true,
    tabelog_url: "",
    google_maps_url: "https://maps.google.com/?q=福の家+秋葉原+神田駿河台",
    website_url: "",
    phone: "03-3233-0044",
    email: "",
    address_en: "5F Sun Royal Bldg, 2-4-4 Kanda-Surugadai, Chiyoda-ku, Tokyo",
    address_ja: "東京都千代田区神田駿河台2-4-4 サンロイヤルビル5F",
    lunch_available: false,
    dinner_available: true,
    tags: ["traditional", "sake-selection"],
    is_premium: false,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "r32",
    name_en: "Roppongi Uoteru",
    name_ja: "六本木 魚てる",
    area: "roppongi",
    area_display_en: "Roppongi",
    area_display_ja: "六本木",
    cuisine: "izakaya",
    cuisine_display_en: "Izakaya",
    cuisine_display_ja: "居酒屋",
    budget_min: 4000,
    budget_max: 6000,
    difficulty: 2,
    rating: 4.3,
    description_en: "A seafood-focused izakaya in Roppongi known for its luxurious uni and ikura earthen pot rice. The calm, modern Japanese interior provides a refined setting for enjoying premium seasonal fish dishes and carefully selected sake.",
    description_ja: "六本木の海鮮居酒屋。名物のウニいくら土鍋ご飯が絶品。落ち着いたモダン和空間で旬の魚介を堪能。",
    booking_method: "online",
    booking_tips_en: "Online booking recommended. The earthen pot rice often sells out so order early. Calm atmosphere compared to busy Roppongi izakayas.",
    english_support: true,
    has_counter: true,
    has_private_room: true,
    tabelog_url: "",
    google_maps_url: "https://maps.google.com/?q=六本木+魚てる",
    website_url: "",
    phone: "03-6447-1030",
    email: "",
    address_en: "B1F, 7-8-5 Roppongi, Minato-ku, Tokyo",
    address_ja: "東京都港区六本木7-8-5 B1F",
    lunch_available: false,
    dinner_available: true,
    tags: ["modern", "sake-selection", "date-spot", "english-menu"],
    is_premium: false,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
];

export const mockMessages: GeneratedMessage[] = [
  {
    id: "m1",
    user_id: "u1",
    restaurant_id: "r3",
    restaurant_name: "Sushi Kanesaka (鮨 かねさか)",
    message_ja: "鮨 かねさか 御中\n\nご予約のお願いを申し上げます。\n\n日時：2026年4月5日（日）19:00\n人数：2名\n\nカウンター席を希望いたします。\n記念日のディナーとして伺いたいと考えております。\n\nご確認のほど、よろしくお願いいたします。\n\nJohn Smith",
    message_en: "Dear Sushi Kanesaka,\n\nI would like to make a reservation.\n\nDate: April 5, 2026 (Sunday) at 19:00\nParty size: 2\n\nWe would prefer counter seats if available.\nThis will be an anniversary dinner.\n\nThank you for your consideration.\n\nJohn Smith",
    reservation_date: "2026-04-05",
    reservation_time: "19:00",
    party_size: 2,
    special_requests: "Counter seat preferred, Anniversary dinner",
    created_at: "2026-03-18T10:30:00Z",
  },
];

// Data fetching functions (to be replaced with API calls later)
export function getRestaurants(filters?: {
  area?: string;
  cuisine?: string;
  budgetMin?: number;
  budgetMax?: number;
}): Restaurant[] {
  let results = mockRestaurants;

  if (filters?.area) {
    const area = filters.area.toLowerCase();
    results = results.filter((r) => r.area === area);
  }
  if (filters?.cuisine) {
    const cuisine = filters.cuisine.toLowerCase();
    results = results.filter((r) => r.cuisine === cuisine);
  }
  if (filters?.budgetMin !== undefined && filters?.budgetMax !== undefined) {
    const min = filters.budgetMin;
    const max = filters.budgetMax;
    results = results.filter((r) => r.budget_max >= min && r.budget_min <= max);
  }

  return results;
}

export function getRestaurantById(id: string): Restaurant | undefined {
  return mockRestaurants.find((r) => r.id === id);
}

export function getMessages(): GeneratedMessage[] {
  return mockMessages;
}

export function generateMockMessage(
  restaurant: Restaurant,
  date: string,
  time: string,
  partySize: number,
  specialRequests: string,
  allergies: string
): { ja: string; en: string } {
  const dateObj = new Date(date);
  const dayNames = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
  const jaDay = ["日", "月", "火", "水", "木", "金", "土"];

  return {
    ja: `${restaurant.name_ja} 御中\n\nご予約のお願いを申し上げます。\n\n日時：${dateObj.getFullYear()}年${dateObj.getMonth() + 1}月${dateObj.getDate()}日（${jaDay[dateObj.getDay()]}）${time}\n人数：${partySize}名\n${specialRequests ? `\nご要望：${specialRequests}\n` : ""}${allergies ? `\nアレルギー・食事制限：${allergies}\n` : ""}\nご確認のほど、よろしくお願いいたします。`,
    en: `Dear ${restaurant.name_en},\n\nI would like to make a reservation.\n\nDate: ${dateObj.toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })} (${dayNames[dateObj.getDay()]}) at ${time}\nParty size: ${partySize}\n${specialRequests ? `\nSpecial requests: ${specialRequests}\n` : ""}${allergies ? `\nAllergies/Dietary restrictions: ${allergies}\n` : ""}\nThank you for your consideration.`,
  };
}
