-- ============================================
-- Tokyo Table Finder - Restaurant Seed Data
-- Generated: 2026-03-24
-- Total: 150+ restaurants across 11 cuisines
-- ============================================

-- SUSHI (22 restaurants)
INSERT INTO restaurants (
  name_en, name_ja, area, area_display_en, area_display_ja,
  cuisine, cuisine_display_en, cuisine_display_ja,
  budget_min, budget_max, difficulty, rating,
  description_en, description_ja,
  booking_method, booking_tips_en,
  english_support, has_counter, has_private_room,
  tabelog_url, google_maps_url, website_url, phone, email,
  address_en, address_ja,
  lunch_available, dinner_available,
  tags, is_premium
) VALUES
-- 1. Sukiyabashi Jiro
(
  'Sukiyabashi Jiro', 'すきやばし次郎',
  'ginza', 'Ginza', '銀座',
  'sushi', 'Sushi', '寿司',
  40000, 55000, 5, 4.8,
  'The legendary sushi restaurant made famous by the documentary ''Jiro Dreams of Sushi,'' now led by Yoshikazu Ono. Located in a basement in Ginza, this intimate 10-seat counter offers an unforgettable Edomae sushi experience.',
  'ドキュメンタリー『二郎は鮨の夢を見る』で世界的に有名になった伝説の寿司店。現在は小野禎一氏が握りを担当。銀座の地下にある10席のカウンターで江戸前鮨の技を堪能できます。',
  'phone', 'Reservations for overseas guests must be made through your hotel concierge. Book at least 1 month in advance.',
  false, true, false,
  NULL, NULL, 'https://www.sushi-jiro.jp/en/shop', '03-3535-3600', NULL,
  'B1F Tsukamoto Sogyo Building, 4-2-15 Ginza, Chuo-ku, Tokyo',
  '東京都中央区銀座4-2-15 塚本総業ビル B1F',
  true, true,
  ARRAY['michelin-3star', 'counter-only', 'reservation-required', 'omakase', 'edo-mae'],
  true
),
-- 2. Sushi Saito
(
  'Sushi Saito', '鮨さいとう',
  'roppongi', 'Roppongi', '六本木',
  'sushi', 'Sushi', '寿司',
  40000, 60000, 5, 4.9,
  'Ranked as one of the best restaurants in the world by La Liste. Chef Takashi Saito''s masterful Edomae technique and pristine ingredient selection are unparalleled. Reservations are essentially impossible without being a regular.',
  'La Listeで世界最高峰のレストランの一つに選ばれた、東京で最も予約困難な鮨店。齋藤孝司氏の卓越した江戸前の技と厳選された素材は他に類を見ません。',
  'phone', 'Essentially impossible to book without a personal connection to a regular. Some luxury concierge services may assist.',
  false, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '1F Ark Hills South Tower, 1-4-5 Roppongi, Minato-ku, Tokyo',
  '東京都港区六本木1-4-5 アークヒルズサウスタワー 1F',
  true, true,
  ARRAY['michelin-3star', 'counter-only', 'reservation-required', 'omakase', 'edo-mae'],
  true
),
-- 3. Sushi Kanesaka
(
  'Sushi Kanesaka', '鮨かねさか',
  'ginza', 'Ginza', '銀座',
  'sushi', 'Sushi', '寿司',
  25000, 45000, 4, 4.7,
  'A two Michelin-starred sushi institution in Ginza known for refined Edomae sushi. Chef Shinji Kanesaka''s precise technique and warm hospitality make this one of Tokyo''s most respected sushi counters.',
  'ミシュラン二つ星の銀座を代表する鮨店。金坂真次氏の正確な技と温かいおもてなしが評価され、東京で最も尊敬される鮨カウンターの一つ。',
  'online', 'Book via their website or reservation platforms like TableAll. Reservations open about 1 month ahead.',
  true, true, true,
  NULL, NULL, 'https://www.sushi-kanesaka.co.jp/en', NULL, NULL,
  'B1F Ginza Misuzu Building, 8-10-3 Ginza, Chuo-ku, Tokyo',
  '東京都中央区銀座8-10-3 銀座三鈴ビル B1F',
  true, true,
  ARRAY['michelin-2star', 'reservation-required', 'omakase', 'edo-mae'],
  true
),
-- 4. Nishiazabu Sushi Shin
(
  'Nishiazabu Sushi Shin', '西麻布 鮨 真',
  'azabu_juban', 'Nishi-Azabu', '西麻布',
  'sushi', 'Sushi', '寿司',
  20000, 40000, 4, 4.6,
  'Newly elevated to two Michelin stars in the 2026 guide. This Nishi-Azabu gem honors traditional Edomae techniques with a modern touch, featuring 8 counter seats, tables, and private tatami rooms.',
  '2026年版ミシュランガイドで二つ星に昇格した西麻布の名店。伝統的な江戸前の技にモダンなアレンジを加えた鮨を提供。',
  'online', 'Reserve through Omakase.in or byFood. Book 2-4 weeks ahead. Closed Mondays.',
  false, true, true,
  NULL, NULL, NULL, NULL, NULL,
  '4-18-20 Nishiazabu, Minato-ku, Tokyo',
  '東京都港区西麻布4-18-20',
  true, true,
  ARRAY['michelin-2star', 'reservation-required', 'omakase', 'edo-mae'],
  false
),
-- 5. Sushi Tokami
(
  'Sushi Tokami', '鮨とかみ',
  'ginza', 'Ginza', '銀座',
  'sushi', 'Sushi', '寿司',
  20000, 35000, 4, 4.5,
  'A Michelin-starred Ginza sushi restaurant famous for exceptional tuna. Chef Hiroyuki Sato uses bold red vinegar rice, creating a distinctive style that tuna lovers adore.',
  '築地市場で培ったマグロの目利きが光るミシュラン一つ星の銀座鮨店。佐藤博之氏は大胆な赤酢のシャリを使い、独自のスタイルを確立。',
  'phone', 'Call 03-3571-6005 to reserve. Book 2-3 weeks ahead for dinner. Omakase only.',
  false, true, false,
  NULL, NULL, NULL, '03-3571-6005', NULL,
  'B1F Seiwa Ginza Silver Building, 8-2-10 Ginza, Chuo-ku, Tokyo',
  '東京都中央区銀座8-2-10 誠和銀座シルバービル B1F',
  true, true,
  ARRAY['michelin-1star', 'reservation-required', 'omakase', 'edo-mae'],
  false
),
-- 6. Manten Sushi Marunouchi
(
  'Manten Sushi Marunouchi', 'まんてん鮨 丸の内',
  'ginza', 'Marunouchi', '丸の内',
  'sushi', 'Sushi', '寿司',
  5000, 12000, 2, 4.3,
  'One of Tokyo''s best-value omakase sushi restaurants in Marunouchi Brick Square. Lunch omakase at around 4,400 yen and dinner at 8,800 yen offer incredible quality.',
  '丸の内ブリックスクエアに位置する東京屈指のコスパ鮨店。ランチおまかせ約4,400円、ディナー約8,800円で本格江戸前鮨が楽しめます。',
  'online', 'Book via TableCheck or call 03-6269-9100. Lunch fills up fast — reserve 1-2 weeks ahead.',
  false, true, false,
  NULL, NULL, NULL, '03-6269-9100', NULL,
  'B1F Marunouchi Brick Square, 2-6-1 Marunouchi, Chiyoda-ku, Tokyo',
  '東京都千代田区丸の内2-6-1 丸の内ブリックスクエア B1F',
  true, true,
  ARRAY['hidden-gem', 'omakase', 'edo-mae'],
  false
),
-- 7. Sushi Tokyo Ten Shibuya
(
  'Sushi Tokyo Ten Shibuya', 'スシトウキョウテン 渋谷店',
  'shibuya', 'Shibuya', '渋谷',
  'sushi', 'Sushi', '寿司',
  5000, 11000, 2, 4.2,
  'A sleek counter-style sushi restaurant inside Shibuya Stream, just 3 minutes from Shibuya Station. Lunch omakase at 4,950 yen offers excellent value.',
  '渋谷ストリーム3Fにある洗練されたカウンター鮨店。ランチおまかせ4,950円で、喧騒を忘れる落ち着いた空間で本格鮨が楽しめます。',
  'online', 'Reserve via TableCheck. Cashless only. Weekday lunch omakase is the best deal.',
  true, true, false,
  NULL, NULL, NULL, '03-5843-1690', NULL,
  '3F Shibuya Stream, 3-21-3 Shibuya, Shibuya-ku, Tokyo',
  '東京都渋谷区渋谷3-21-3 渋谷ストリーム 3F',
  true, true,
  ARRAY['omakase', 'edo-mae'],
  false
),
-- 8. Sushidokoro Issekisancho
(
  'Sushidokoro Issekisancho', '鮨処 一石三鳥',
  'ginza', 'Shinbashi', '新橋',
  'sushi', 'Sushi', '寿司',
  8000, 12000, 2, 4.3,
  'A polished sushi counter in Shinbashi offering Ginza-quality sushi at friendlier prices. The 9,800 yen omakase includes eight pieces of nigiri and eight tsumami dishes.',
  '新橋にある銀座クオリティの鮨を手頃な価格で楽しめるカウンター鮨店。おまかせ9,800円で握り8貫とつまみ8品が楽しめます。',
  'online', 'Reserve via TableCheck. Three seatings: 16:30, 18:45, and 21:00.',
  false, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '1F Shinbashi Four One Building, 4-20-2 Shinbashi, Minato-ku, Tokyo',
  '東京都港区新橋4-20-2 新橋フォーワンビル 1F',
  false, true,
  ARRAY['omakase', 'hidden-gem'],
  false
),
-- 9. Sushi Fukuju Shinjuku
(
  'Sushi Fukuju Shinjuku', '鮨 福寿 新宿店',
  'shinjuku', 'Shinjuku', '新宿',
  'sushi', 'Sushi', '寿司',
  5000, 10000, 2, 4.1,
  'A well-regarded sushi restaurant near Shinjuku Station West Exit, known for exceptional sea urchin and bluefin tuna sourced fresh from Toyosu Market every morning.',
  '新宿駅西口から徒歩3分の人気鮨店。毎朝豊洲市場で仕入れるウニと本マグロが自慢。カウンター・テーブル・個室の計24席。',
  'online', 'Reserve via byFood or call directly. Lunch courses from 7,980 yen are great value.',
  false, true, true,
  NULL, NULL, NULL, NULL, NULL,
  'Daikanplaza City 104 II, 7-20-16 Nishishinjuku, Shinjuku-ku, Tokyo',
  '東京都新宿区西新宿7-20-16 大観プラザシティ104 II',
  true, true,
  ARRAY['omakase', 'hidden-gem'],
  false
),
-- 10. Ginza Iwa
(
  'Ginza Iwa', '銀座いわ',
  'ginza', 'Ginza', '銀座',
  'sushi', 'Sushi', '寿司',
  12000, 15000, 3, 4.4,
  'A Michelin one-star sushi counter with just seven seats, offering an intimate omakase experience in the heart of Ginza at relatively approachable prices.',
  '銀座の中心にあるミシュラン一つ星、わずか7席のカウンター鮨店。銀座にしては手頃な価格で特別な食体験を提供します。',
  'online', 'Book via TableAll or Pocket Concierge. Only 7 seats so reserve 2-3 weeks ahead.',
  false, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '1F Miura Building, 8-4-4 Ginza, Chuo-ku, Tokyo',
  '東京都中央区銀座8-4-4 三浦ビル 1F',
  true, true,
  ARRAY['michelin-1star', 'counter-only', 'reservation-required', 'omakase', 'edo-mae'],
  false
),
-- 11. Sushi Arai
(
  'Sushi Arai', '鮨あらい',
  'ginza', 'Ginza', '銀座',
  'sushi', 'Sushi', '寿司',
  10000, 15000, 3, 4.5,
  'A Michelin one-star restaurant by young chef Yuichi Arai, who trained at Ginza Kyubey. The second-floor counter is accessible through reservation platforms.',
  '銀座久兵衛で修行した若き職人・新井祐一氏のミシュラン一つ星店。予約サイト経由で2階カウンターは予約可能。',
  'online', 'Main counter is regulars-only, but the 2nd counter (B1F) is bookable via Omakase.in or byFood.',
  false, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '2F Ruan Building, 8-10-2 Ginza, Chuo-ku, Tokyo',
  '東京都中央区銀座8-10-2 ルアンビル 2F',
  false, true,
  ARRAY['michelin-1star', 'reservation-required', 'omakase', 'edo-mae'],
  false
),
-- 12. Sushi Oya
(
  'Sushi Oya', '鮨おうや',
  'shinjuku', 'Kagurazaka', '神楽坂',
  'sushi', 'Sushi', '寿司',
  10000, 15000, 3, 4.4,
  'Newly awarded one Michelin star in the 2026 guide. The chef grew up overseas and brings a unique global perspective to Edomae sushi with creative creations.',
  '2026年ミシュラン一つ星を新たに獲得した革新的な鮨店。海外育ちの店主が江戸前鮨にグローバルな視点を取り入れている。',
  'phone', 'Call 03-6228-1868 to reserve. Newly starred so demand is high — book 3-4 weeks ahead.',
  true, true, false,
  NULL, NULL, NULL, '03-6228-1868', NULL,
  '3F, 3-6 Fukuromachi, Shinjuku-ku, Tokyo',
  '東京都新宿区袋町3-6 3F',
  false, true,
  ARRAY['michelin-1star', 'reservation-required', 'omakase', 'edo-mae', 'hidden-gem'],
  false
),
-- 13. Sushi Yuki
(
  'Sushi Yuki', '鮨ゆき',
  'ebisu', 'Hiroo', '広尾',
  'sushi', 'Sushi', '寿司',
  10000, 15000, 3, 4.4,
  'Freshly awarded one Michelin star in 2026, this 9-seat hinoki cypress counter is a serene haven. Traditional hagama pot rice with rice vinegar creates clean, bright acidity.',
  '2026年ミシュラン一つ星を獲得した、檜カウンター9席の静謐な空間。羽釜で炊いたシャリに米酢を合わせた清々しい酸味が特徴。',
  'phone', 'Reservation only, 9 seats. Newly starred so popularity is surging — book 3+ weeks ahead.',
  false, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '5-17-4 Hiroo, Shibuya-ku, Tokyo',
  '東京都渋谷区広尾5-17-4',
  false, true,
  ARRAY['michelin-1star', 'counter-only', 'reservation-required', 'omakase'],
  false
),
-- 14. Bentenyama Miyakozushi
(
  'Bentenyama Miyakozushi', '弁天山美家古寿司',
  'asakusa', 'Asakusa', '浅草',
  'sushi', 'Sushi', '寿司',
  5000, 15000, 2, 4.2,
  'One of Tokyo''s oldest Edomae sushi restaurants, operating in Asakusa since the Edo period. Authentic traditional sushi at surprisingly reasonable prices with English-friendly staff.',
  '江戸時代から浅草で営業する東京最古級の江戸前鮨店。伝統的な鮨を手頃な価格で提供。英語対応スタッフあり。',
  'phone', 'Walk-ins possible but calling ahead recommended. English-speaking staff available. Closed Mondays.',
  true, true, true,
  NULL, NULL, NULL, NULL, NULL,
  '2-1-16 Asakusa, Taito-ku, Tokyo',
  '東京都台東区浅草2-1-16',
  true, true,
  ARRAY['edo-mae', 'hidden-gem'],
  false
),
-- 15. Numazuko Shinjuku Honten
(
  'Numazuko Shinjuku Honten', '沼津港 新宿本店',
  'shinjuku', 'Shinjuku', '新宿',
  'sushi', 'Sushi', '寿司',
  2000, 5000, 1, 3.9,
  'A premium conveyor-belt sushi restaurant near Shinjuku Station with exceptionally fresh seafood from Numazu port. Quality is a step above typical kaiten-zushi.',
  '新宿駅至近の回転寿司店。沼津港直送の新鮮な魚介を使い、一般的な回転寿司よりワンランク上の品質。',
  'walk-in', 'No reservations — walk-in only. Open 11:00-22:30 daily. Expect a 15-30 min wait at peak hours.',
  false, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '1F Ikeda Plaza Building, 3-34-16 Shinjuku, Shinjuku-ku, Tokyo',
  '東京都新宿区新宿3-34-16 池田プラザビル 1F',
  true, true,
  ARRAY['conveyor-belt', 'casual'],
  false
),
-- 16. Sushi Dai
(
  'Sushi Dai', '寿司大',
  'tsukiji', 'Toyosu Market', '豊洲市場',
  'sushi', 'Sushi', '寿司',
  2500, 5000, 2, 4.5,
  'The most famous sushi restaurant inside Toyosu Fish Market. The 4,500 yen omakase features nine pieces of the day''s freshest catch. Arrive before 7 AM for shorter queues.',
  '豊洲市場内で最も有名な寿司店。おまかせ4,500円で、その日の最高のネタ9貫を大将が選んで握ります。7時前の到着推奨。',
  'walk-in', 'No reservations. Arrive before 7 AM. Closed Wednesdays and Sundays. English menu available.',
  true, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '6-5-1 Toyosu, Koto-ku, Tokyo (Toyosu Market)',
  '東京都江東区豊洲6-5-1 豊洲市場 水産仲卸売場棟',
  true, false,
  ARRAY['hidden-gem', 'edo-mae', 'omakase'],
  false
),
-- 17. Motodane
(
  'Motodane', '本種',
  'tsukiji', 'Tsukiji', '築地',
  'sushi', 'Sushi', '寿司',
  1000, 3000, 1, 4.0,
  'A beloved local sushi spot hidden in the backstreets near Tsukiji Outer Market. Fresh, affordable chirashi bowls from around 1,000 yen. Cash only.',
  '築地場外市場近くの路地裏に佇む地元民に愛される寿司店。ちらし丼約1,000円から新鮮なネタが楽しめます。現金のみ。',
  'walk-in', 'Walk-in only, cash only. Open 10:30-14:00 and 17:30-21:00. Closed Wednesdays.',
  false, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '6-25-4 Tsukiji, Chuo-ku, Tokyo',
  '東京都中央区築地6-25-4',
  true, true,
  ARRAY['casual', 'hidden-gem'],
  false
),
-- 18. Sushi Katsura
(
  'Sushi Katsura', '寿司かつら',
  'tsukiji', 'Tsukiji', '築地',
  'sushi', 'Sushi', '寿司',
  950, 5000, 1, 4.0,
  'Incredible-value sushi near the old Tsukiji Fish Market. The lunch set of 9 nigiri and 1 maki roll for just 950 yen is legendary among budget-savvy visitors.',
  '旧築地市場からすぐの驚異的コスパの寿司店。ランチの握り9貫と巻き1本のセットがわずか950円は伝説的。',
  'walk-in', 'Walk-in only. Cash recommended. Lunch opens 11:30.',
  false, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '2-15-4 Tsukiji, Chuo-ku, Tokyo',
  '東京都中央区築地2-15-4',
  true, true,
  ARRAY['casual', 'hidden-gem'],
  false
),
-- 19. Magurobito Okachimachi
(
  'Magurobito Okachimachi', 'まぐろ人 御徒町出張所',
  'ueno', 'Ueno (Ameyoko)', '上野（アメ横）',
  'sushi', 'Sushi', '寿司',
  500, 3000, 1, 3.9,
  'A lively standing sushi bar in Ueno''s Ameyoko market specializing in tuna. Lean tuna 200 yen, medium fatty 290 yen, fatty tuna just 400 yen per piece.',
  '上野アメ横にある活気ある立ち食い寿司店。赤身200円、中トロ290円、大トロ400円から一貫ずつ注文可能。',
  'walk-in', 'Standing only, no reservations. Open from 4:30 AM on weekdays. Very casual.',
  false, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '6-3-7 Ueno, Taito-ku, Tokyo',
  '東京都台東区上野6-3-7',
  true, true,
  ARRAY['standing-sushi', 'casual'],
  false
),
-- 20. Hidezushi
(
  'Hidezushi', '秀寿司',
  'ueno', 'Ueno (Ameyoko)', '上野（アメ横）',
  'sushi', 'Sushi', '寿司',
  1000, 4000, 1, 4.0,
  'A beloved local sushi restaurant next to Ameyoko market. Prices are clearly displayed and surprisingly low for the quality. The fatty mackerel is a must-try.',
  '上野アメ横のすぐそばにある地元民に愛される寿司店。価格は明確に表示され、品質に対して驚くほどリーズナブル。',
  'walk-in', 'Walk-in only. Prices displayed clearly — no surprise charges.',
  false, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '6-7-8 Ueno, Taito-ku, Tokyo',
  '東京都台東区上野6-7-8',
  true, true,
  ARRAY['casual', 'hidden-gem'],
  false
),
-- 21. Umegaoka Sushi no Midori Shibuya
(
  'Umegaoka Sushi no Midori Shibuya', '梅丘寿司の美登利 渋谷店',
  'shibuya', 'Shibuya', '渋谷',
  'sushi', 'Sushi', '寿司',
  2000, 5000, 1, 4.1,
  'Founded in 1977, famous for generous portions at low prices. The omakase nigiri set at 3,600 yen is legendary. Numbered tickets distributed at the door.',
  '1977年創業、大ぶりのネタとリーズナブルな価格で有名。おまかせ握りセット3,600円は圧倒的人気。整理券制で行列必至。',
  'walk-in', 'No reservations — numbered tickets distributed at the door. Arrive 30+ min before opening.',
  false, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '4F Shibuya Mark City, 1-12-3 Dogenzaka, Shibuya-ku, Tokyo',
  '東京都渋谷区道玄坂1-12-3 渋谷マークシティ 4F',
  true, true,
  ARRAY['casual'],
  false
),
-- 22. Sushi Nakamura
(
  'Sushi Nakamura', '鮨なかむら',
  'roppongi', 'Roppongi', '六本木',
  'sushi', 'Sushi', '寿司',
  5000, 12000, 3, 4.5,
  'A Michelin one-star sushi restaurant with just 11 seats led by self-taught chef Masanori Nakamura. His steamed abalone with liver sauce is legendary.',
  '六本木にあるミシュラン一つ星、わずか11席の鮨店。独学で技を磨いた中村正則氏が握る。アワビの肝ソース蒸しは絶品。',
  'online', 'Reserve via byFood or TableCheck. Book 2-3 weeks in advance.',
  true, true, false,
  NULL, NULL, NULL, '03-3746-0856', NULL,
  '7-17-16 Roppongi, Minato-ku, Tokyo',
  '東京都港区六本木7-17-16',
  true, true,
  ARRAY['michelin-1star', 'counter-only', 'reservation-required', 'omakase'],
  false
),

-- RAMEN (22 restaurants)
-- 23. Fuunji
(
  'Fuunji', '風雲児',
  'shinjuku', 'Shinjuku', '新宿',
  'ramen', 'Ramen', 'ラーメン',
  800, 1100, 3, 4.5,
  'One of Tokyo''s most acclaimed tsukemen shops, famous for its incredibly rich fish-based dipping broth. The queue often wraps around the block.',
  '東京で最も評価の高いつけ麺店の一つ。濃厚な魚介スープが有名。行列は長いですが格別の一杯。',
  'walk-in', 'Use the ticket machine at the entrance. Arrive 30 minutes before opening. Noodle size (200g-400g) same price.',
  true, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '2-14-3 Yoyogi, Shibuya-ku, Tokyo',
  '東京都渋谷区代々木2-14-3 北斗第一ビル1F',
  true, true,
  ARRAY['tsukemen', 'niboshi', 'queue-famous'],
  false
),
-- 24. Rokurinsha
(
  'Rokurinsha', '六厘舎',
  'ginza', 'Tokyo Station', '東京駅',
  'ramen', 'Ramen', 'ラーメン',
  900, 1300, 2, 4.3,
  'The undisputed king of Tokyo Ramen Street under Tokyo Station. Legendary tsukemen with thick, chewy noodles and rich pork-seafood dipping broth. Breakfast ramen from 7:30am.',
  '東京ラーメンストリートの王者。濃厚な豚骨魚介のつけ汁と太くてもちもちの麺が人気。朝7時半から朝ラーメンも。',
  'walk-in', 'Come for breakfast ramen (7:30-9:30am) to avoid the 30-60 minute lunch queue.',
  true, true, false,
  NULL, NULL, NULL, NULL, NULL,
  'B1 First Avenue Tokyo Station, 1-9-1 Marunouchi, Chiyoda-ku, Tokyo',
  '東京都千代田区丸の内1-9-1 東京駅一番街B1F 東京ラーメンストリート',
  true, true,
  ARRAY['tsukemen', 'tonkotsu', 'queue-famous'],
  false
),
-- 25. Ginza Kagari
(
  'Ginza Kagari', '銀座 篝',
  'ginza', 'Ginza', '銀座',
  'ramen', 'Ramen', 'ラーメン',
  1000, 1500, 3, 4.5,
  'A Ginza backstreet gem famous for its creamy Tori Paitan chicken broth soba that resembles a French bisque. Only 8 counter seats.',
  '銀座の裏路地にある名店。クリーミーな鶏白湯そばが看板。U字型カウンター8席のみの小さな空間。',
  'walk-in', 'Only 8 seats, expect long waits. Arrive by 10:30am for the 11am opening. Ticket machine.',
  false, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '6-4-12 Ginza, Chuo-ku, Tokyo',
  '東京都中央区銀座6-4-12',
  true, true,
  ARRAY['shoyu', 'shio', 'queue-famous'],
  false
),
-- 26. Nakiryu
(
  'Nakiryu', '鳴龍',
  'ikebukuro', 'Otsuka', '大塚',
  'ramen', 'Ramen', 'ラーメン',
  900, 1400, 3, 4.6,
  'The second ramen shop in Tokyo to earn a Michelin star, famous for outstanding tantanmen with rich sesame and chili broth. Tiny 10-seat shop.',
  '東京で2番目にミシュランの星を獲得したラーメン店。濃厚なゴマと唐辛子のスープの担々麺が絶品。10席の小さな店。',
  'walk-in', 'Only 10 seats, arrive well before 11am opening. Closed Tuesdays. Ticket machine ordering.',
  false, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '2-34-4 Minamiotsuka, Toshima-ku, Tokyo',
  '東京都豊島区南大塚2-34-4 SKY南大塚',
  true, false,
  ARRAY['michelin', 'tantanmen', 'queue-famous'],
  false
),
-- 27. Sobahouse Konjiki Hototogisu
(
  'Sobahouse Konjiki Hototogisu', 'SOBA HOUSE 金色不如帰',
  'shinjuku', 'Shinjuku Gyoenmae', '新宿御苑前',
  'ramen', 'Ramen', 'ラーメン',
  1000, 1500, 3, 4.6,
  'The third ramen shop in the world to earn a Michelin star. Shio soba combines hamaguri clam and sea bream dashi. Shoyu soba features truffle sauce and porcini oil.',
  '世界で3番目にミシュランの星を獲得したラーメン店。蛤と真鯛の出汁の塩そばが看板。醤油そばにはトリュフとポルチーニ。',
  'walk-in', 'Expect 30-45 minute queues. Between Shinjuku-gyoenmae and Shinjuku-sanchome stations. Ticket machine.',
  false, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '2-4-1 Shinjuku, Shinjuku-ku, Tokyo',
  '東京都新宿区新宿2-4-1 第22宮庭マンション1階105号室',
  true, true,
  ARRAY['michelin', 'shio', 'shoyu', 'queue-famous'],
  false
),
-- 28. Ramen Hayashi
(
  'Ramen Hayashi', 'はやし',
  'shibuya', 'Shibuya', '渋谷',
  'ramen', 'Ramen', 'ラーメン',
  900, 1200, 2, 4.4,
  'Widely considered the best ramen in Shibuya since 2003. Thick, rich pork-chicken-fish blended broth with a hint of orange peel. Eat quickly and leave.',
  '2003年の創業以来、渋谷最高のラーメンと評される名店。豚・鶏・魚介ブレンドの濃厚スープにオレンジの皮のアクセント。',
  'walk-in', 'Open only until soup runs out (usually by 3:30pm). Closed Wednesdays, Sundays, and holidays.',
  false, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '1-14-9 Dogenzaka, Shibuya-ku, Tokyo',
  '東京都渋谷区道玄坂1-14-9 1F',
  true, false,
  ARRAY['shoyu', 'queue-famous'],
  false
),
-- 29. Menya Musashi Shinjuku Honten
(
  'Menya Musashi Shinjuku Honten', '麺屋武蔵 新宿本店',
  'shinjuku', 'Shinjuku', '新宿',
  'ramen', 'Ramen', 'ラーメン',
  900, 1500, 2, 4.2,
  'The original 1998 flagship known for bold double-soup ramen combining pork bone and dried fish broths. Samurai-themed atmosphere.',
  '1998年創業の麺屋武蔵の本店。豚骨と魚介のダブルスープが看板。武士テーマの店内の雰囲気も魅力。',
  'walk-in', 'Ticket machine at entrance. 4-minute walk from Shinjuku Station West Exit. Open until 10:30pm.',
  true, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '7-2-6 Nishishinjuku, Shinjuku-ku, Tokyo',
  '東京都新宿区西新宿7-2-6 K-1ビル1F',
  true, true,
  ARRAY['tonkotsu', 'niboshi', 'queue-famous'],
  false
),
-- 30. Japanese Soba Noodles Tsuta
(
  'Japanese Soba Noodles Tsuta', 'Japanese Soba Noodles 蔦',
  'shibuya', 'Yoyogi-Uehara', '代々木上原',
  'ramen', 'Ramen', 'ラーメン',
  1000, 1500, 2, 4.4,
  'The world''s first Michelin-starred ramen shop (2015). Elegant shoyu soba with a refined truffle-tinged broth. A pilgrimage site for ramen enthusiasts.',
  '2015年に世界で初めてミシュランの星を獲得したラーメン店。トリュフの香りが漂う上品な醤油そばが看板。',
  'walk-in', '3-minute walk from Yoyogi-Uehara Station. Closed Thursdays. Opens 11am-5pm.',
  false, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '3-2-4 Nishihara, Shibuya-ku, Tokyo',
  '東京都渋谷区西原3-2-4 フロンティア代々木上原B1F',
  true, false,
  ARRAY['michelin', 'shoyu', 'queue-famous'],
  false
),
-- 31. Karashibi Miso Ramen Kikanbo
(
  'Karashibi Miso Ramen Kikanbo', 'カラシビ味噌らー麺 鬼金棒',
  'kanda', 'Kanda', '神田',
  'ramen', 'Ramen', 'ラーメン',
  900, 1300, 2, 4.3,
  'A thrilling spicy miso ramen where you customize chili heat and numbing Sichuan peppercorn levels. Demon-themed interior with oni masks and red lighting.',
  '辛さと痺れのレベルを自分で選べるスパイシー味噌ラーメンの名店。鬼の面と赤い照明が五感を刺激する独特の体験。',
  'walk-in', 'Cash only. Always has a queue. 3-minute walk from Kanda Station. Start with ''less'' spice if new to it.',
  false, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '2-10-10 Kajicho, Chiyoda-ku, Tokyo',
  '東京都千代田区鍛冶町2-10-10',
  true, true,
  ARRAY['miso', 'queue-famous', 'late-night'],
  false
),
-- 32. Taishoken Honten
(
  'Taishoken Honten', '東池袋大勝軒 本店',
  'ikebukuro', 'Ikebukuro', '池袋',
  'ramen', 'Ramen', 'ラーメン',
  800, 1100, 2, 4.2,
  'The legendary birthplace of tsukemen, founded by the ''God of Ramen'' Kazuo Yamagishi. A must-visit pilgrimage for ramen history.',
  '「ラーメンの神様」山岸一雄が創業した、つけ麺発祥の伝説的な名店。ラーメンの歴史を味わいたい方には必訪の聖地。',
  'walk-in', '1-2 minutes from Higashi-Ikebukuro Station. Ticket machine ordering. Portions are generous.',
  false, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '2-42-8 Minamiikebukuro, Toshima-ku, Tokyo',
  '東京都豊島区南池袋2-42-8',
  true, true,
  ARRAY['tsukemen', 'shoyu', 'queue-famous'],
  false
),
-- 33. Homemade Ramen Muginae
(
  'Homemade Ramen Muginae', 'Homemade Ramen 麦苗',
  'ebisu', 'Omori', '大森',
  'ramen', 'Ramen', 'ラーメン',
  800, 1200, 1, 4.5,
  'A Michelin Bib Gourmand ramen hidden near Omori Station. MSG-free broth uses premium katsuobushi, niboshi, and kombu for pure, clean flavor.',
  '大森駅近くのミシュラン・ビブグルマンのラーメン店。化学調味料不使用のスープは澄んだ旨味が楽しめる隠れた名店。',
  'walk-in', '7-minute walk from Omori-Kaigan Station. Open 11:00-15:30 only. Closed Wednesdays and Thursdays.',
  false, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '6-11-10 Minamioi, Shinagawa-ku, Tokyo',
  '東京都品川区南大井6-11-10',
  true, false,
  ARRAY['hidden-gem', 'shoyu', 'niboshi'],
  false
),
-- 34. Ramen Kamo to Negi
(
  'Ramen Kamo to Negi', 'らーめん鴨to葱',
  'ueno', 'Ueno', '上野',
  'ramen', 'Ramen', 'ラーメン',
  1000, 1500, 1, 4.4,
  'Tokyo''s best duck ramen, under the train tracks near Okachimachi. Pure broth uses only duck, water, and negi. Open 24 hours.',
  '御徒町駅近くの高架下にある東京最高の鴨ラーメン店。鴨・水・葱だけで作る澄んだスープが絶品。24時間営業。',
  'walk-in', 'Open 24 hours daily. 11 counter seats. Ticket machine. Under the train tracks.',
  false, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '6-4-15 Ueno, Taito-ku, Tokyo',
  '東京都台東区上野6-4-15',
  true, true,
  ARRAY['hidden-gem', 'shio', 'late-night'],
  false
),
-- 35. Miso Ramen Kakitagawa Hibari
(
  'Miso Ramen Kakitagawa Hibari', '味噌ラーメン 柿田川ひばり 恵比寿本店',
  'ebisu', 'Ebisu', '恵比寿',
  'ramen', 'Ramen', 'ラーメン',
  900, 1300, 1, 4.3,
  'An elegant miso ramen in Ebisu that treats miso as fine art. Five types of miso blended with no-heat process. Interior with piano music feels like a cafe.',
  '恵比寿にある上品な味噌ラーメン店。5種類の味噌を非加熱製法でブレンド。ピアノ音楽が流れる洗練された空間。',
  'walk-in', '3-minute walk from JR Ebisu Station West Exit. Limited lunch hours (11:30-15:00). Ticket machine.',
  false, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '1-10-8 Ebisu-Nishi, Shibuya-ku, Tokyo',
  '東京都渋谷区恵比寿西1-10-8 杉山ビル1F',
  true, false,
  ARRAY['hidden-gem', 'miso'],
  false
),
-- 36. Kaimen Mikawa
(
  'Kaimen Mikawa', '貝麺みかわ',
  'shimokitazawa', 'Shimokitazawa', '下北沢',
  'ramen', 'Ramen', 'ラーメン',
  900, 1200, 1, 4.3,
  'A cozy 7-seat clam ramen specialist in Shimokitazawa. Shoyu broth combines asari clam and beef stock for deep umami.',
  '下北沢のわずか7席の貝ラーメン専門店。あさりと牛骨のスープを合わせた醤油ブロスは深い旨味が特徴。',
  'walk-in', '1-minute walk from Shimokitazawa Station. Only 7 seats. Ticket machine. Cashless accepted.',
  false, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '2-25-4 Kitazawa, Setagaya-ku, Tokyo',
  '東京都世田谷区北沢2-25-4',
  true, true,
  ARRAY['hidden-gem', 'shoyu', 'shio'],
  false
),
-- 37. Men Mitsui
(
  'Men Mitsui', '麺 みつヰ',
  'asakusa', 'Asakusa', '浅草',
  'ramen', 'Ramen', 'ラーメン',
  900, 1300, 2, 4.5,
  'One of Tokyo''s finest shoyu ramen shops, hidden in Asakusa backstreets. The semi-transparent shoyu broth is so refined that pilgrims travel from across Japan.',
  '浅草の裏通りに隠れた東京最高峰の醤油ラーメン店の一つ。半透明に輝く醤油スープの完成度は圧巻。',
  'walk-in', '6-minute walk from Asakusa Station (Toei line). Lunch only on Sundays. Closed Mondays.',
  false, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '2-10-4 Nishi-Asakusa, Taito-ku, Tokyo',
  '東京都台東区西浅草2-10-4',
  true, true,
  ARRAY['hidden-gem', 'shoyu'],
  false
),
-- 38. Ramen Yoroiya
(
  'Ramen Yoroiya', 'ラーメン与ろゐ屋',
  'asakusa', 'Asakusa', '浅草',
  'ramen', 'Ramen', 'ラーメン',
  800, 1100, 1, 4.2,
  'A beloved local ramen institution in Asakusa, frequented by neighborhood regulars. Traditional Tokyo-style shoyu ramen, a genuine taste of old-school Asakusa.',
  '浅草の地元民に愛される老舗ラーメン店。正統派の東京醤油ラーメンは懐かしくて本格的な味わい。',
  'walk-in', 'Located in central Asakusa near Senso-ji. Ticket machine. Less crowded than tourist-facing spots.',
  false, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '1-36-7 Asakusa, Taito-ku, Tokyo',
  '東京都台東区浅草1-36-7',
  true, true,
  ARRAY['hidden-gem', 'shoyu'],
  false
),
-- 39. Ichikoro
(
  'Ichikoro', '一虎 156',
  'azabu_juban', 'Azabu-Juban', '麻布十番',
  'ramen', 'Ramen', 'ラーメン',
  900, 1300, 1, 4.2,
  'The undisputed best ramen in Azabu-Juban, serving rich and creamy tori paitan chicken broth in an upscale neighborhood.',
  '麻布十番で最高のラーメンと評される店。クリーミーな鶏白湯ラーメンが自慢。六本木・麻布エリアの隠れた名店。',
  'walk-in', '5-minute walk from Azabu-Juban Station. Less crowded than major ramen spots. Ticket machine.',
  false, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '1-5-6 Azabu-Juban, Minato-ku, Tokyo',
  '東京都港区麻布十番1-5-6',
  true, true,
  ARRAY['hidden-gem', 'tonkotsu'],
  false
),
-- 40. Mensho Tokyo
(
  'Mensho Tokyo', '自家製麺 MENSHO TOKYO',
  'shinjuku', 'Korakuen', '後楽園',
  'ramen', 'Ramen', 'ラーメン',
  1000, 1500, 2, 4.4,
  'A ramen laboratory near Tokyo Dome where the chef experiments with unconventional ingredients. Groundbreaking lamb ramen blends tonkotsu and lamb bones.',
  '東京ドーム近くのラーメン研究所。看板のラムラーメンは豚骨とラム骨をブレンドした独創的な一杯。',
  'walk-in', '1-minute walk from Exit 6 of Korakuen Station. Menu changes based on experimentation.',
  true, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '1-2-8 Kasuga, Bunkyo-ku, Tokyo',
  '東京都文京区春日1-2-8',
  true, true,
  ARRAY['tonkotsu', 'shio'],
  false
),
-- 41. Iruca Tokyo Roppongi
(
  'Iruca Tokyo Roppongi', '入鹿TOKYO 六本木',
  'roppongi', 'Roppongi', '六本木',
  'ramen', 'Ramen', 'ラーメン',
  1200, 2000, 2, 4.5,
  'A Michelin Bib Gourmand ramen that feels like kaiseki. Porcini shoyu ramen features lobster and Wagyu beef broth with black truffle paste. Founded by a former rock guitarist.',
  'ミシュラン・ビブグルマンのラーメン店。ポルチーニ醤油ラーメンはロブスターと和牛のブロスに黒トリュフペースト。元ロックギタリストが創業。',
  'walk-in', 'Near Tokyo Midtown. Often 1+ hour wait. Closed Mondays. Last order 19:40.',
  true, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '4-12-12 Roppongi, Minato-ku, Tokyo',
  '東京都港区六本木4-12-12',
  true, true,
  ARRAY['michelin', 'shoyu', 'queue-famous'],
  false
),
-- 42. Soranoiro Nippon
(
  'Soranoiro Nippon', 'ソラノイロ NIPPON',
  'ginza', 'Tokyo Station', '東京駅',
  'ramen', 'Ramen', 'ラーメン',
  1000, 1500, 2, 4.1,
  'A pioneering ramen on Tokyo Ramen Street offering vegan, vegetarian, and gluten-free options. Colorful veggie ramen with soy-milk noodles. Perfect for mixed dietary needs.',
  '東京ラーメンストリートにある革新的な店。ヴィーガン・ベジタリアン・グルテンフリー対応。豆乳麺を使ったカラフルな野菜ラーメン。',
  'walk-in', 'Located in Tokyo Ramen Street (B1F Tokyo Station). Open 8:30-22:30. English menu with photos.',
  true, true, false,
  NULL, NULL, NULL, NULL, NULL,
  'B1F First Avenue Tokyo Station, 1-9-1 Marunouchi, Chiyoda-ku, Tokyo',
  '東京都千代田区丸の内1-9-1 東京駅一番街B1F 東京ラーメンストリート',
  true, true,
  ARRAY['vegan-option', 'shio', 'shoyu'],
  false
),
-- 43. Sugoi Niboshi Ramen Nagi Golden Gai
(
  'Sugoi Niboshi Ramen Nagi Golden Gai', 'すごい煮干ラーメン凪 新宿ゴールデン街店本館',
  'shinjuku', 'Shinjuku Golden Gai', '新宿ゴールデン街',
  'ramen', 'Ramen', 'ラーメン',
  1000, 1400, 2, 4.3,
  'Intensely flavorful niboshi ramen on the 2nd floor of an old wooden house in Golden Gai bar district. Over 20 types of sardines boiled for 12 hours. Open 24 hours.',
  '新宿ゴールデン街の木造家屋2階にある強烈な煮干しラーメンの名店。20種類以上の煮干しを12時間煮込んだスープ。24時間営業。',
  'walk-in', 'Open 24 hours. 2nd floor of a wooden building in Golden Gai. 3-minute walk from Shinjuku-sanchome Station.',
  true, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '2F, 1-1-10 Kabukicho, Shinjuku-ku, Tokyo',
  '東京都新宿区歌舞伎町1-1-10 2F',
  true, true,
  ARRAY['niboshi', 'late-night'],
  false
),
-- 44. Taiyou no Tomato-men
(
  'Taiyou no Tomato-men', '太陽のトマト麺',
  'shinjuku', 'Shinjuku', '新宿',
  'ramen', 'Ramen', 'ラーメン',
  1000, 1500, 2, 4.0,
  'Italian-inspired ramen with vibrant tomato-based broth blended with chicken paitan. Tomato Cheese Ramen topped with cheese and basil. Perfect for adventurous eaters.',
  'トマトベースのスープと鶏白湯を合わせたイタリアン風ラーメン。看板のトマトチーズラーメンは新しいラーメン体験。',
  'walk-in', 'Multiple Shinjuku locations. Soy-milk noodles give a unique texture.',
  true, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '1-19-1 Kabukicho, Shinjuku-ku, Tokyo',
  '東京都新宿区歌舞伎町1-19-1 新宿東宝ビル',
  true, true,
  ARRAY['vegan-option', 'shoyu'],
  false
),

-- YAKITORI (18 restaurants)
-- 45. Torishiki
(
  'Torishiki', '鳥しき',
  'nakameguro', 'Meguro', '目黒',
  'yakitori', 'Yakitori', '焼き鳥',
  8000, 15000, 5, 4.8,
  'Tokyo''s most legendary yakitori restaurant, holding a Michelin star since 2010. Chef Ikegawa serves omakase at a 12-seat counter. Reservations months in advance.',
  '2010年からミシュラン一つ星を維持する東京最高峰の焼き鳥店。池川氏が12席のカウンターでおまかせを提供。予約は数ヶ月先まで。',
  'phone', 'Phone reservations only, opens bookings two months in advance. Lines are extremely busy.',
  false, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '2-14-12 Kamiosaki, Shinagawa-ku, Tokyo',
  '東京都品川区上大崎2-14-12',
  false, true,
  ARRAY['michelin', 'reservation-required', 'counter-only', 'charcoal-grilled'],
  true
),
-- 46. Bird Land
(
  'Bird Land', 'バードランド',
  'ginza', 'Ginza', '銀座',
  'yakitori', 'Yakitori', '焼き鳥',
  8000, 15000, 4, 4.6,
  'The first yakitori restaurant to earn a Michelin star. Chef Wada serves premium Okushiiba chicken grilled over binchotan charcoal in a refined Ginza basement.',
  '焼き鳥店として史上初のミシュラン一つ星を獲得した名店。銀座駅直結の地下で奥志賀地鶏を備長炭で焼き上げる。',
  'phone', 'Reserve by phone at least two weeks ahead. Closed Sunday, Monday, and holidays.',
  false, true, false,
  NULL, NULL, NULL, NULL, NULL,
  'B1F, 4-2-15 Ginza, Chuo-ku, Tokyo 104-0061',
  '東京都中央区銀座4-2-15 B1F',
  false, true,
  ARRAY['michelin', 'reservation-required', 'counter-only', 'charcoal-grilled', 'date-spot'],
  true
),
-- 47. Yakitori Omino
(
  'Yakitori Omino', '焼鳥おみ乃',
  'asakusa', 'Oshiage', '押上',
  'yakitori', 'Yakitori', '焼き鳥',
  10000, 18000, 5, 4.7,
  'Michelin-starred yakitori near Skytree. Unique omakase with about 20 varieties — no menu, the chef grills until you say stop.',
  'スカイツリー近くのミシュラン一つ星焼き鳥店。メニューはなく、約20種の串をおまかせで提供。食べた分だけお会計。',
  'online', 'Reservations open on the 1st business day of each month for two months ahead. Book via OMAKASE platform.',
  false, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '1-38-4 Oshiage, Sumida-ku, Tokyo 131-0045',
  '東京都墨田区押上1-38-4',
  false, true,
  ARRAY['michelin', 'reservation-required', 'counter-only', 'charcoal-grilled', 'hidden-gem'],
  true
),
-- 48. Ebisu Torihiro
(
  'Ebisu Torihiro', '恵比寿 鳥廣',
  'ebisu', 'Ebisu', '恵比寿',
  'yakitori', 'Yakitori', '焼き鳥',
  10000, 15000, 4, 4.5,
  'An intimate 8-seat counter yakitori from the Torishiki lineage. Beautiful single-slab wood counter with premium chicken and sake pairings.',
  '鳥しき系列で修業したシェフが営む8席のカウンター焼き鳥店。一枚板のカウンターで地鶏と日本酒のペアリング。',
  'online', 'Book through TABLEALL or OMAKASE. Reservation only; closed Mondays.',
  false, true, true,
  NULL, NULL, NULL, NULL, NULL,
  '1-22-1 Ebisu, Shibuya-ku, Tokyo',
  '東京都渋谷区恵比寿1-22-1',
  false, true,
  ARRAY['reservation-required', 'counter-only', 'charcoal-grilled', 'date-spot', 'hidden-gem'],
  true
),
-- 49. Ginza Yakitori Kyotamba
(
  'Ginza Yakitori Kyotamba', '銀座焼とり京丹波',
  'ginza', 'Ginza', '銀座',
  'yakitori', 'Yakitori', '焼き鳥',
  12000, 20000, 3, 4.4,
  'Premium yakitori in Ginza opened in 2024, serving rare Takasaka Chicken from Kyoto. About 17 items including chicken sashimi.',
  '2024年開業の銀座の高級焼き鳥店。京丹波地方の希少な高坂鶏を使用し、約17品のおまかせコースを提供。',
  'online', 'Book via OMAKASE platform. Smart casual dress code; guests must be 18+.',
  false, true, true,
  NULL, NULL, NULL, NULL, NULL,
  '201 Ginza Granbell Square, 7-2-18 Ginza, Chuo-ku, Tokyo 104-0061',
  '東京都中央区銀座7-2-18 銀座グランベルスクエア201',
  false, true,
  ARRAY['reservation-required', 'charcoal-grilled', 'date-spot'],
  false
),
-- 50. Yakitori Shin
(
  'Yakitori Shin', '焼鳥しん',
  'shinjuku', 'Shinjuku', '新宿',
  'yakitori', 'Yakitori', '焼き鳥',
  4000, 6000, 2, 4.3,
  'Refined yakitori near Shinjuku-Gyoenmae using premium Kumano Jidori chicken from Mie Prefecture. The signature tsukune with egg yolk is a must-try.',
  '新宿御苑前駅近くの焼き鳥店。三重県産の熊野地鶏を使用。名物のつくねは卵黄と合わせて絶品。',
  'online', 'Reservations via TableCheck. Walk-ins possible but booking recommended for counter.',
  false, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '1-16-9 Shinjuku, Shinjuku-ku, Tokyo',
  '東京都新宿区新宿1-16-9 寿御苑前ビル1F',
  false, true,
  ARRAY['charcoal-grilled', 'date-spot', 'hidden-gem'],
  false
),
-- 51. Yakitori Imai
(
  'Yakitori Imai', '焼鳥今井',
  'omotesando', 'Omotesando', '表参道',
  'yakitori', 'Yakitori', '焼き鳥',
  5000, 6000, 2, 4.4,
  'Stylish yakitori near Gaienmae Station proving chicken skewers can be gourmet fare. Perfect for visitors exploring the Omotesando area.',
  '外苑前駅近くのスタイリッシュな焼き鳥店。洗練された雰囲気で上質な焼き鳥を楽しめる。',
  'online', 'Reservations via OpenTable or phone. Closed Sunday and Monday.',
  false, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '3-42-11 Jingumae, Rosa Bianca 1F, Shibuya-ku, Tokyo',
  '東京都渋谷区神宮前3-42-11 ローザビアンカ1F',
  false, true,
  ARRAY['charcoal-grilled', 'date-spot', 'hidden-gem'],
  false
),
-- 52. Torisawa Roppongi
(
  'Torisawa Roppongi', '鳥沢 六本木',
  'roppongi', 'Roppongi', '六本木',
  'yakitori', 'Yakitori', '焼き鳥',
  4000, 6000, 2, 4.2,
  'Tabelog''s 100 Best Yakitori selection. Each chicken part is cut and grilled differently. Signature grilled rice ball finale is a highlight.',
  '食べログ百名店に選出された鳥沢の六本木店。鶏の各部位ごとに異なるカットと焼き方。〆の焼きおにぎりが名物。',
  'online', 'Reserve via TableCheck. Stop system — pay based on how much you consume.',
  true, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '4-1-19 Roppongi, ARUGA 19 Bldg. 1F, Minato-ku, Tokyo',
  '東京都港区六本木4-1-19 ARUGA19ビル1F',
  false, true,
  ARRAY['charcoal-grilled', 'casual'],
  false
),
-- 53. Yakitori Bunraku
(
  'Yakitori Bunraku', '焼鳥文楽',
  'ueno', 'Ueno', '上野',
  'yakitori', 'Yakitori', '焼き鳥',
  2000, 3000, 1, 3.9,
  'A beloved yakitori institution in Ueno''s Ameyoko market since 1958. Affordable charcoal-grilled skewers under the train tracks. English picture menu.',
  '1958年創業、上野アメ横の老舗焼き鳥店。高架下の活気ある雰囲気でリーズナブルな炭火焼き鳥。写真付き英語メニューあり。',
  'walk-in', 'No reservations. Arrive early on weekends. Open from lunch on weekends.',
  true, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '6-12-1 Ueno, Taito-ku, Tokyo',
  '東京都台東区上野6-12-1',
  true, true,
  ARRAY['casual', 'charcoal-grilled', 'hidden-gem'],
  false
),
-- 54. Yasubee
(
  'Yasubee', 'やすべえ',
  'shinjuku', 'Shinjuku', '新宿',
  'yakitori', 'Yakitori', '焼き鳥',
  2000, 3000, 1, 3.7,
  'Iconic spot in Shinjuku''s Omoide Yokocho (Memory Lane). The owner is accustomed to foreign visitors — a great first yakitori experience.',
  '新宿・思い出横丁の名物焼き鳥店。昭和レトロな雰囲気で外国人観光客にも慣れた店主が迎えてくれる。',
  'walk-in', 'No reservations; walk-in only. Seats fill fast after 7 PM. Point and order at the counter.',
  true, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '1-2 Nishishinjuku, Shinjuku-ku, Tokyo (Omoide Yokocho)',
  '東京都新宿区西新宿1-2 思い出横丁内',
  false, true,
  ARRAY['casual', 'charcoal-grilled', 'standing', 'hidden-gem'],
  false
),
-- 55. Toriyoshi Nakameguro
(
  'Toriyoshi Nakameguro', '鳥よし 中目黒本店',
  'nakameguro', 'Nakameguro', '中目黒',
  'yakitori', 'Yakitori', '焼き鳥',
  3000, 5000, 1, 4.0,
  'No-reservation yakitori in trendy Nakameguro, beloved by locals for decades. Anyone can casually drop in for excellent charcoal-grilled chicken.',
  '中目黒で長年地元に愛される焼き鳥店。予約不可がポリシーで、誰でも気軽に炭火焼き鳥を楽しめる。',
  'walk-in', 'No reservations by policy. Walk-in only. Open from 5 PM weekdays, 4:30 PM weekends.',
  false, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '2-8-6 Kamimeguro, Meguro-ku, Tokyo',
  '東京都目黒区上目黒2-8-6 谷島ビル1F',
  false, true,
  ARRAY['casual', 'charcoal-grilled'],
  false
),
-- 56. Torifuku (Nonbei Yokocho)
(
  'Torifuku', '鳥福',
  'shibuya', 'Shibuya', '渋谷',
  'yakitori', 'Yakitori', '焼き鳥',
  2000, 3000, 1, 3.8,
  'Historic yakitori in Shibuya''s Nonbei Yokocho (Drunkard''s Alley) since 1932. Authentic retro Tokyo drinking experience in a 2-meter-wide lane.',
  '1932年創業、渋谷・のんべい横丁の老舗焼き鳥店。幅2メートルの路地でレトロな昭和の雰囲気を味わえる。',
  'walk-in', 'Walk-in only. Arrive before 7 PM on weekdays. Cash preferred.',
  false, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '1-25 Shibuya, Shibuya-ku, Tokyo (Nonbei Yokocho)',
  '東京都渋谷区渋谷1-25 のんべい横丁内',
  false, true,
  ARRAY['casual', 'charcoal-grilled', 'hidden-gem', 'standing'],
  false
),
-- 57. Sumibi Yakitori Odori
(
  'Sumibi Yakitori Odori', '炭火焼鳥おどり',
  'ikebukuro', 'Ikebukuro', '池袋',
  'yakitori', 'Yakitori', '焼き鳥',
  3000, 5000, 1, 4.0,
  'Charcoal-grilled yakitori specialist near Ikebukuro Station using premium Daisen chicken from Tottori over Kishu binchotan.',
  '池袋駅西口徒歩3分の炭火焼き鳥専門店。鳥取県産の大山鶏を紀州備長炭で一本一本丁寧に焼き上げる。',
  'phone', 'Phone reservations recommended for groups. Walk-ins welcome for counter.',
  false, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '1-17-1 Nishiikebukuro, Toshima-ku, Tokyo',
  '東京都豊島区西池袋1-17-1',
  false, true,
  ARRAY['casual', 'charcoal-grilled'],
  false
),
-- 58. Higonoya Aoyama
(
  'Higonoya Aoyama', 'ひご乃屋 青山本店',
  'omotesando', 'Omotesando', '表参道',
  'yakitori', 'Yakitori', '焼き鳥',
  3000, 5000, 1, 3.9,
  'Yakitori izakaya with over 58 years of history, 4-minute walk from Omotesando Station. Affordable quality in Tokyo''s most fashionable neighborhood.',
  '表参道駅から徒歩4分、創業58年以上の老舗焼き鳥居酒屋。おしゃれエリアで気軽に本格焼き鳥を楽しめる。',
  'phone', 'Phone reservations accepted. Walk-ins possible but may wait during peak hours.',
  false, true, true,
  NULL, NULL, NULL, NULL, NULL,
  '5-51-8 Jingumae, Shibuya-ku, Tokyo',
  '東京都渋谷区神宮前5-51-8',
  true, true,
  ARRAY['casual', 'charcoal-grilled'],
  false
),
-- 59. Toritama Honkan
(
  'Toritama Honkan', '鳥玉本館',
  'ebisu', 'Shirokane', '白金',
  'yakitori', 'Yakitori', '焼き鳥',
  4000, 6000, 2, 4.3,
  'Michelin Bib Gourmand yakitori in Shirokane with over 20 varieties of rare chicken cuts. Stylish monotone interior with jazz music.',
  'ミシュラン・ビブグルマン獲得の白金の焼き鳥店。20種類以上の希少部位をモノトーンの洗練された空間で。',
  'phone', 'Extremely popular. Call well in advance. Counter seating only.',
  false, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '6-22-19 Shirokane, Minato-ku, Tokyo',
  '東京都港区白金6-22-19',
  false, true,
  ARRAY['charcoal-grilled', 'counter-only', 'date-spot', 'hidden-gem'],
  false
),
-- 60. Motsu-yaki Ucchan
(
  'Motsu-yaki Ucchan', 'もつ焼き うっちゃん',
  'shinjuku', 'Shinjuku', '新宿',
  'yakitori', 'Yakitori', '焼き鳥',
  2000, 3000, 1, 3.8,
  'Tiny grilled skewer shop in Omoide Yokocho known for Negi Liver — fresh chicken liver with yuzu kosho. Smoky, authentic yokocho experience.',
  '思い出横丁の小さなもつ焼き店。名物のネギレバーは新鮮な鶏レバーを柚子胡椒で焼き上げた逸品。',
  'walk-in', 'Walk-in only. Very small, be prepared to wait or come early.',
  false, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '1-2 Nishishinjuku, Shinjuku-ku, Tokyo (Omoide Yokocho)',
  '東京都新宿区西新宿1-2 思い出横丁内',
  false, true,
  ARRAY['casual', 'charcoal-grilled', 'standing', 'hidden-gem'],
  false
),
-- 61. Trunk Kushi
(
  'Trunk Kushi', 'トランク クシ',
  'shibuya', 'Shibuya', '渋谷',
  'yakitori', 'Yakitori', '焼き鳥',
  3000, 5000, 1, 3.9,
  'Neo-retro yakitori inside Trunk Hotel between Shibuya and Harajuku. Stylish with drinks from 600 yen and dishes from 300 yen.',
  'トランクホテル内のネオレトロな焼き鳥店。渋谷のソウルフードへのオマージュをコンセプトにスタイリッシュな空間。',
  'walk-in', 'Walk-ins welcome. Inside Trunk Hotel. Open for both lunch and dinner.',
  true, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '5-31 Jingumae, Shibuya-ku, Tokyo (Trunk Hotel)',
  '東京都渋谷区神宮前5-31 トランクホテル内',
  true, true,
  ARRAY['casual', 'date-spot'],
  false
),
-- 62. Torifuku Ueno
(
  'Torifuku Ueno', '鳥福 上野',
  'ueno', 'Ueno', '上野',
  'yakitori', 'Yakitori', '焼き鳥',
  2500, 4000, 1, 3.8,
  'Authentic izakaya-style yakitori in Ueno with a wide variety of grilled chicken and classic pub fare. Great after visiting Ueno Park.',
  '上野の本格居酒屋風焼き鳥店。焼き鳥を中心に多彩な居酒屋メニュー。上野公園巡りの後にぴったり。',
  'phone', 'Phone reservations for groups. Walk-ins fine for small parties.',
  false, true, true,
  NULL, NULL, NULL, NULL, NULL,
  '6-8-2 Ueno, Taito-ku, Tokyo',
  '東京都台東区上野6-8-2',
  false, true,
  ARRAY['casual', 'charcoal-grilled'],
  false
),

-- TEMPURA (12 restaurants)
-- 63. Tempura Kondo
(
  'Tempura Kondo', 'てんぷら近藤',
  'ginza', 'Ginza', '銀座',
  'tempura', 'Tempura', '天ぷら',
  15000, 30000, 4, 4.7,
  'Legendary two-Michelin-starred counter tempura in Ginza, famous for exceptionally light batter and renowned vegetable tempura since 1991.',
  '銀座にあるミシュラン二つ星の天ぷらカウンター。薄衣の野菜天ぷらが名物。近藤氏自ら目の前で一品ずつ揚げる。',
  'phone', 'Book through hotel concierge or call 03-5568-0923 between 12:00-17:00.',
  false, true, false,
  NULL, NULL, 'https://tempura-kondo.com/en/', '03-5568-0923', NULL,
  '9F Sakaguchi Building, 5-5-13 Ginza, Chuo-ku, Tokyo',
  '東京都中央区銀座5-5-13 坂口ビル9F',
  true, true,
  ARRAY['michelin-2star', 'counter', 'omakase', 'vegetable-tempura'],
  true
),
-- 64. Tempura Fukamachi
(
  'Tempura Fukamachi', '天ぷら深町',
  'ginza', 'Kyobashi', '京橋',
  'tempura', 'Tempura', '天ぷら',
  12000, 20000, 4, 4.6,
  'Michelin one-star counter-only tempura with just 12 seats near Kyobashi. Chef adjusts batter ratio for each ingredient with remarkable precision.',
  '京橋駅近くのミシュラン一つ星カウンター天ぷら。わずか12席で、食材に応じて衣の割合を変える繊細な技。',
  'online', 'Reservations via web form on fukamachi-japan.com. Credit card required at booking.',
  false, true, false,
  NULL, NULL, 'https://fukamachi-japan.com/en', NULL, NULL,
  '1F A-M Kyobashi Building, 2-5-2 Kyobashi, Chuo-ku, Tokyo',
  '東京都中央区京橋2-5-2 A・M京橋ビル1F',
  true, true,
  ARRAY['michelin-1star', 'counter-only', 'omakase', 'edomae'],
  true
),
-- 65. Tempura Motoyoshi
(
  'Tempura Motoyoshi', '天ぷら元吉',
  'omotesando', 'Minami-Aoyama', '南青山',
  'tempura', 'Tempura', '天ぷら',
  15000, 25000, 4, 4.7,
  'Two-Michelin-starred tempura near Gaienmae. The chef insists on personal reservations only — no agents or proxies allowed.',
  '外苑前駅近くのミシュラン二つ星天ぷら。本人予約のみ受付という徹底したこだわり。',
  'phone', 'Call 03-6455-0200. Reservations open one month in advance. Must be made by the guest personally.',
  false, true, false,
  NULL, NULL, NULL, '03-6455-0200', NULL,
  '3F Granbell Ebisu IV, 2-8-11 Ebisunishi, Shibuya-ku, Tokyo',
  '東京都渋谷区恵比寿西2-8-11 グランベル恵比寿IV 3F',
  false, true,
  ARRAY['michelin-2star', 'counter', 'omakase', 'reservation-strict'],
  true
),
-- 66. Tempura Mikawa Keyakizaka
(
  'Tempura Mikawa Keyakizaka', 'てんぷらみかわ けやき坂店',
  'roppongi', 'Roppongi', '六本木',
  'tempura', 'Tempura', '天ぷら',
  12000, 22000, 3, 4.5,
  'In Roppongi Hills, run by the eldest son of legendary ''God of Tempura'' Chef Saotome. Counter and private room seating with Edomae-style tempura.',
  '六本木ヒルズ内の名店。「天ぷらの神様」早乙女氏の長男が腕を振るう江戸前天ぷら。',
  'online', 'Reserve via TableCheck or call. Private rooms available for 2-8 guests.',
  true, true, true,
  NULL, NULL, NULL, NULL, NULL,
  '3F Roppongi Hills Residence B, 6-12-2 Roppongi, Minato-ku, Tokyo',
  '東京都港区六本木6-12-2 六本木ヒルズレジデンスB 3F',
  true, true,
  ARRAY['michelin', 'counter', 'private-room', 'edomae'],
  false
),
-- 67. Tenichi Ginza Honten
(
  'Tenichi Ginza Honten', '天一 銀座本店',
  'ginza', 'Ginza', '銀座',
  'tempura', 'Tempura', '天ぷら',
  10000, 20000, 3, 4.3,
  'Established in 1930, one of Tokyo''s most historic tempura institutions with nearly a century of tradition.',
  '1930年創業の老舗天ぷら料理店。銀座本店は伝統を守りながら常に革新を追求。',
  'phone', 'Call 03-3571-1949. 3-minute walk from Ginza Station B6 exit.',
  true, true, true,
  NULL, NULL, NULL, '03-3571-1949', NULL,
  '6-6-5 Ginza, Chuo-ku, Tokyo',
  '東京都中央区銀座6-6-5',
  true, true,
  ARRAY['historic', 'since-1930', 'counter', 'private-room'],
  false
),
-- 68. Tsunahachi Sohonten
(
  'Tsunahachi Sohonten', '天ぷら新宿つな八 総本店',
  'shinjuku', 'Shinjuku', '新宿',
  'tempura', 'Tempura', '天ぷら',
  2000, 5000, 1, 4.1,
  'A beloved Shinjuku institution since 1923. Authentic tempura at reasonable prices — queues at peak hours but worth the wait. English menu.',
  '1923年創業の新宿の老舗天ぷら店。リーズナブルな価格で本格天ぷらが楽しめる名店。',
  'walk-in', 'No reservations needed. Located near Shinjuku Station East Exit. English menu available.',
  true, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '3-31-8 Shinjuku, Shinjuku-ku, Tokyo',
  '東京都新宿区新宿3-31-8',
  true, true,
  ARRAY['historic', 'since-1923', 'walk-in', 'affordable', 'english-menu'],
  false
),
-- 69. Kaneko Hannosuke
(
  'Kaneko Hannosuke', '金子半之助',
  'tsukiji', 'Nihonbashi', '日本橋',
  'tempura', 'Tempura', '天ぷら',
  1500, 2500, 1, 4.2,
  'Tokyo''s most famous tendon shop with generous portions at incredibly low prices. Lines stretch for hours. A must-visit budget tempura.',
  '東京で最も有名な天丼専門店。驚きのコスパとボリュームで常に大行列。',
  'walk-in', 'No reservations — queue only. Arrive before 11am. Cash preferred.',
  true, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '1-11-15 Nihonbashi Muromachi, Chuo-ku, Tokyo',
  '東京都中央区日本橋室町1-11-15',
  true, true,
  ARRAY['tendon', 'walk-in', 'budget', 'queue-famous'],
  false
),
-- 70. Daikokuya Tempura
(
  'Daikokuya Tempura', '大黒家天麩羅',
  'asakusa', 'Asakusa', '浅草',
  'tempura', 'Tempura', '天ぷら',
  1500, 3000, 1, 4.0,
  'An Asakusa icon since 1887 near Senso-ji, famous for dark sesame-oil-fried tempura with a rich sweet-and-salty house sauce.',
  '1887年創業の浅草の老舗天ぷら店。ごま油で揚げた濃い色の天ぷらと甘辛い秘伝のタレが名物。',
  'walk-in', 'No reservations. 4-minute walk from Asakusa Station. Open 11am-8pm daily.',
  true, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '1-38-10 Asakusa, Taito-ku, Tokyo',
  '東京都台東区浅草1-38-10',
  true, true,
  ARRAY['historic', 'since-1887', 'walk-in', 'sesame-oil', 'tendon'],
  false
),
-- 71. Tenkichiya
(
  'Tenkichiya', '天吉屋',
  'shinjuku', 'Nishi-Shinjuku', '西新宿',
  'tempura', 'Tempura', '天ぷら',
  1500, 3000, 1, 3.9,
  'Popular tendon specialist in the Shinjuku Nomura Building with generous bowls packed with jumbo shrimp and seasonal vegetables.',
  '新宿野村ビル地下の天丼専門店。大海老と季節の野菜がたっぷりの天丼が人気。',
  'walk-in', 'No reservations needed. B2F of Shinjuku Nomura Building. Closed Sundays.',
  true, true, false,
  NULL, NULL, NULL, NULL, NULL,
  'B2F Shinjuku Nomura Building, 1-26-2 Nishi-Shinjuku, Shinjuku-ku, Tokyo',
  '東京都新宿区西新宿1-26-2 新宿野村ビルB2F',
  true, true,
  ARRAY['tendon', 'walk-in', 'budget', 'quick-meal'],
  false
),
-- 72. Tempura Yamanoue Roppongi
(
  'Tempura Yamanoue Roppongi', 'てんぷら山の上 六本木',
  'roppongi', 'Roppongi', '六本木',
  'tempura', 'Tempura', '天ぷら',
  3000, 5000, 2, 4.2,
  'Refined yet approachable tempura inside Tokyo Midtown. Excellent lunch sets from around 2,275 yen with counter seating.',
  '東京ミッドタウン内の天ぷら店。ランチセット2,275円からとリーズナブル。カウンターで職人の技を間近に。',
  'online', 'Reservations recommended for dinner. Walk-ins possible for lunch. Direct connection to Roppongi Station.',
  true, true, true,
  NULL, NULL, NULL, NULL, NULL,
  '3F Tokyo Midtown Garden Terrace, 9-7-4 Akasaka, Minato-ku, Tokyo',
  '東京都港区赤坂9-7-4 東京ミッドタウン ガーデンテラス3F',
  true, true,
  ARRAY['midtown', 'counter', 'lunch-deal'],
  false
),
-- 73. Tempura Abe Ginza Honten
(
  'Tempura Abe Ginza Honten', '天ぷら阿部 銀座本店',
  'ginza', 'Ginza', '銀座',
  'tempura', 'Tempura', '天ぷら',
  2000, 5000, 2, 4.1,
  'Michelin Bib Gourmand tempura in Ginza by a chef with 30 years experience from Nadaman. Authentic counter tempura at mid-range prices.',
  'なだ万出身のベテラン職人が腕を振るう銀座の天ぷら店。ミシュランビブグルマン掲載。本格天ぷらを手頃な価格で。',
  'online', 'Reservations recommended for dinner. 1-minute walk from Ginza Station A10. English menu available.',
  true, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '4-3-7 Ginza, Chuo-ku, Tokyo',
  '東京都中央区銀座4-3-7',
  true, true,
  ARRAY['bib-gourmand', 'counter', 'affordable-ginza', 'english-menu'],
  false
),
-- 74. Tempura Tento
(
  'Tempura Tento', '天藤',
  'asakusa', 'Asakusa', '浅草',
  'tempura', 'Tempura', '天ぷら',
  2000, 3000, 1, 3.8,
  'A local favorite near Asakusa Station with generous, well-priced tempura. Great stop for tourists wanting authentic, no-fuss tempura.',
  '浅草駅近くの地元で愛される天ぷら店。ボリュームたっぷりの天丼がお手頃価格。浅草観光のお供に。',
  'walk-in', 'No reservations needed. Closed Mondays. Cash recommended.',
  false, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '1-2-8 Asakusa, Taito-ku, Tokyo',
  '東京都台東区浅草1-2-8',
  true, true,
  ARRAY['walk-in', 'local-favorite', 'casual', 'tendon'],
  false
),

-- KAISEKI (12 restaurants)
-- 75. Kohaku
(
  'Kohaku', '虎白',
  'shinjuku', 'Kagurazaka', '神楽坂',
  'kaiseki', 'Kaiseki', '懐石',
  25000, 40000, 4, 4.8,
  'Three-Michelin-starred kaiseki in charming Kagurazaka, helmed by Japan''s youngest-ever three-star chef Koji Koizumi. Classic kaiseki with avant-garde twist.',
  '神楽坂のミシュラン三つ星懐石料理店。史上最年少で三つ星を獲得した小泉功二氏による、伝統と革新が融合した懐石。',
  'phone', 'Use hotel concierge or TABLEALL. Closed Sundays and holidays. 3 min from Iidabashi Station.',
  false, true, true,
  NULL, NULL, NULL, NULL, NULL,
  '3-4 Kagurazaka, Shinjuku-ku, Tokyo',
  '東京都新宿区神楽坂3-4',
  false, true,
  ARRAY['michelin-3star', 'kagurazaka', 'avant-garde', 'omakase'],
  true
),
-- 76. Kagurazaka Ishikawa
(
  'Kagurazaka Ishikawa', '神楽坂 石かわ',
  'shinjuku', 'Kagurazaka', '神楽坂',
  'kaiseki', 'Kaiseki', '懐石',
  25000, 45000, 5, 4.8,
  'Three-Michelin-starred kaiseki. Chef Ishikawa''s principle of ''mui-shizen'' (true to nature) creates cuisine of profound simplicity with light, elegant flavors.',
  'ミシュラン三つ星の懐石料理店。石川氏の「無為自然」の精神が生む素材の本質を活かした繊細な料理。',
  'phone', 'Call 03-5225-0173 or use hotel concierge/TABLEALL. Dinner only. Closed Sundays and holidays.',
  false, true, true,
  NULL, NULL, NULL, '03-5225-0173', NULL,
  '1F Takamura Building, 5-37 Kagurazaka, Shinjuku-ku, Tokyo',
  '東京都新宿区神楽坂5-37 高村ビル1F',
  false, true,
  ARRAY['michelin-3star', 'kagurazaka', 'minimalist', 'nature-focused'],
  true
),
-- 77. Nihonryori RyuGin
(
  'Nihonryori RyuGin', '日本料理 龍吟',
  'ginza', 'Hibiya', '日比谷',
  'kaiseki', 'Kaiseki', '懐石',
  30000, 50000, 4, 4.8,
  'Three-Michelin-starred kaiseki on the 7th floor of Tokyo Midtown Hibiya. Chef Seiji Yamamoto blends tradition with molecular techniques. No perfume allowed.',
  '東京ミッドタウン日比谷7階のミシュラン三つ星日本料理店。山本征治氏による伝統と革新が融合した12品のコース。',
  'phone', 'Call 03-6630-0007 between 12:00-17:00. Reservations open 1st of each month. Perfume prohibited.',
  true, false, true,
  NULL, NULL, NULL, '03-6630-0007', NULL,
  '7F Tokyo Midtown Hibiya, 1-1-2 Yurakucho, Chiyoda-ku, Tokyo',
  '東京都千代田区有楽町1-1-2 東京ミッドタウン日比谷7F',
  false, true,
  ARRAY['michelin-3star', 'molecular', 'seasonal', 'no-perfume', 'dress-code'],
  true
),
-- 78. Myojaku
(
  'Myojaku', '妙寂',
  'roppongi', 'Nishi-Azabu', '西麻布',
  'kaiseki', 'Kaiseki', '懐石',
  35000, 50000, 5, 4.9,
  'Tokyo''s newest three-Michelin-starred kaiseki, promoted in the 2026 guide. Uses pristine submarine spring water and seasonal ingredients.',
  '2026年ミシュランで三つ星に昇格した最新の注目懐石店。海底湧水を使用し、調和と純粋さを体現。',
  'phone', 'Extremely difficult since the 3-star promotion. Use TABLEALL or hotel concierge.',
  false, true, true,
  NULL, NULL, NULL, NULL, NULL,
  'B1F, 3-2-34 Nishiazabu, Minato-ku, Tokyo',
  '東京都港区西麻布3-2-34 B1F',
  false, true,
  ARRAY['michelin-3star', 'new-3star-2026', 'seasonal'],
  true
),
-- 79. Azabu Yukimura
(
  'Azabu Yukimura', '麻布幸村',
  'azabu_juban', 'Azabu Juban', '麻布十番',
  'kaiseki', 'Kaiseki', '懐石',
  25000, 40000, 4, 4.7,
  'Three-Michelin-starred kappo/kaiseki with only nine counter seats. Chef trained 25 years in Kyoto, sources most ingredients from there.',
  '麻布十番のミシュラン三つ星割烹。京都で25年修行した幸村氏が京都から取り寄せた食材で本格京料理を提供。',
  'phone', 'Only 9 counter seats. Use hotel concierge or TABLEALL.',
  false, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '3F Takayanagi Building, 1-5-5 Azabu Juban, Minato-ku, Tokyo',
  '東京都港区麻布十番1-5-5 高柳ビル3F',
  false, true,
  ARRAY['michelin-3star', 'kappo', 'kyoto-style', 'counter', 'intimate'],
  true
),
-- 80. Ginza Kojyu
(
  'Ginza Kojyu', '銀座小十',
  'ginza', 'Ginza', '銀座',
  'kaiseki', 'Kaiseki', '懐石',
  20000, 35000, 4, 4.6,
  'Two-Michelin-starred kaiseki by Chef Toru Okuda celebrating Japan''s four seasons. Eight counter seats and three private rooms in elegant Ginza.',
  '銀座のミシュラン二つ星懐石料理店。奥田透氏が全国の厳選食材で四季を表現。カウンター8席と個室3室。',
  'phone', 'Reserve through hotel concierge or TABLEALL. 3 min from Ginza Station B6 exit.',
  false, true, true,
  NULL, NULL, NULL, NULL, NULL,
  '4F Carioka Building, 5-4-8 Ginza, Chuo-ku, Tokyo',
  '東京都中央区銀座5-4-8 カリオカビル4F',
  true, true,
  ARRAY['michelin-2star', 'ginza', 'seasonal', 'private-room'],
  true
),
-- 81. Den
(
  'Den', '傳',
  'shibuya', 'Jingumae', '神宮前',
  'kaiseki', 'Kaiseki', '懐石',
  20000, 30000, 4, 4.7,
  'Playful, innovative Michelin-starred kaiseki by Chef Zaiyu Hasegawa. Famous for foie gras monaka and ''tea-ramisu.'' A uniquely fun fine-dining experience.',
  '長谷川在佑氏のミシュラン一つ星の創作懐石。フォアグラ最中やティーラミスなど遊び心あふれる料理。',
  'phone', 'Call between 12pm-5pm Mon-Sat for reservations up to 2 months ahead. Book early.',
  true, true, true,
  NULL, NULL, 'https://www.jimbochoden.com/en/', NULL, NULL,
  '2-3-18 Jingumae, Shibuya-ku, Tokyo',
  '東京都渋谷区神宮前2-3-18',
  false, true,
  ARRAY['michelin-1star', 'creative', 'playful', 'worlds-best', 'innovative'],
  false
),
-- 82. Narisawa
(
  'Narisawa', 'ナリサワ',
  'omotesando', 'Minami-Aoyama', '南青山',
  'kaiseki', 'Kaiseki', '懐石',
  25000, 45000, 4, 4.7,
  'Two-Michelin-starred ''innovative satoyama cuisine'' celebrating Japan''s rural hillscapes. Fuses French haute cuisine with Japanese ingredients sustainably.',
  'ミシュラン二つ星の革新的里山料理。成澤由浩氏がフランス料理と日本の食材を融合させた、サステナブルな美食体験。',
  'online', 'Book via official website (narisawa-yoshihiro.com). Smart casual dress code.',
  true, false, true,
  NULL, NULL, 'https://narisawa-yoshihiro.com', NULL, NULL,
  '2-6-15 Minami-Aoyama Garden Court, Minato-ku, Tokyo',
  '東京都港区南青山2-6-15 南青山ガーデンコート',
  true, true,
  ARRAY['michelin-2star', 'innovative', 'satoyama', 'sustainable', 'french-japanese'],
  true
),
-- 83. Waketokuyama
(
  'Waketokuyama', '分とく山',
  'ebisu', 'Minami-Azabu', '南麻布',
  'kaiseki', 'Kaiseki', '懐石',
  15000, 25000, 3, 4.5,
  'Michelin-starred kaiseki since 1989. More approachable than many high-end spots with refined but not overly formal service. Great kaiseki introduction.',
  '1989年創業の南麻布のミシュラン一つ星懐石料理店。洗練されながらも堅苦しくない雰囲気で懐石入門にも最適。',
  'online', 'Reserve via waketoku.com or by phone. 5 min from Hiroo Station.',
  false, true, true,
  NULL, NULL, 'https://waketoku.com/en', NULL, NULL,
  '5-1-5 Minami-Azabu, Minato-ku, Tokyo',
  '東京都港区南麻布5-1-5',
  true, true,
  ARRAY['michelin-1star', 'since-1989', 'seasonal', 'approachable'],
  false
),
-- 84. Tenoshima
(
  'Tenoshima', 'てのしま',
  'omotesando', 'Minami-Aoyama', '南青山',
  'kaiseki', 'Kaiseki', '懐石',
  10000, 15000, 2, 4.4,
  'Michelin-starred kaiseki reimagined as casual. Nine-course tasting menu at 10,000 yen changes every fortnight. Chef trained under Kikunoi''s Murata.',
  'ミシュラン一つ星ながら手頃な価格の懐石。菊乃井出身の林氏による9品コースが1万円。2週間ごとにメニュー変更。',
  'phone', 'Call 03-6316-2150. 3 min from Aoyama-itchome Station. More accessible pricing.',
  false, true, false,
  NULL, NULL, NULL, '03-6316-2150', NULL,
  '2F, 1-3-21 Minami-Aoyama, Minato-ku, Tokyo',
  '東京都港区南青山1-3-21 南青山1-55ビル2F',
  false, true,
  ARRAY['michelin-1star', 'affordable-michelin', 'omakase'],
  false
),
-- 85. Inshotei
(
  'Inshotei', '韻松亭',
  'ueno', 'Ueno', '上野',
  'kaiseki', 'Kaiseki', '懐石',
  3000, 10000, 2, 4.1,
  'Historic kaiseki since 1875 inside Ueno Park. Affordable lunch sets from under 2,000 yen. Tatami rooms overlook greenery. Vegetarian options.',
  '1875年創業の上野公園内の老舗。2,000円以下のランチセットから楽しめる手頃な懐石。緑を望む座敷。',
  'walk-in', 'Reservations for 4+, otherwise walk in. No credit cards. Vegetarian options available.',
  true, false, true,
  NULL, NULL, 'https://www.innsyoutei.jp/en/', NULL, NULL,
  '4-59 Ueno Park, Taito-ku, Tokyo',
  '東京都台東区上野公園4-59',
  true, true,
  ARRAY['historic', 'since-1875', 'ueno-park', 'budget-kaiseki', 'vegetarian-option'],
  false
),
-- 86. Yakumo Saryo
(
  'Yakumo Saryo', '八雲茶寮',
  'nakameguro', 'Yakumo (Meguro)', '八雲（目黒）',
  'kaiseki', 'Kaiseki', '懐石',
  8000, 15000, 2, 4.3,
  'Beautifully designed teahouse-restaurant by famed designer Shinichiro Ogata. Seasonal kaiseki lunch followed by Japanese sweets and tea. Dinner is invitation-only.',
  'デザイナー緒方慎一郎氏が手掛けた茶寮。季節の懐石ランチと和菓子・お茶が楽しめる。夜は紹介制。',
  'phone', 'Call 03-5731-1620 for lunch. Lunch only for first-time visitors. Open 9am-5pm.',
  false, false, true,
  NULL, NULL, NULL, '03-5731-1620', NULL,
  '3-4-7 Yakumo, Meguro-ku, Tokyo',
  '東京都目黒区八雲3-4-7',
  true, false,
  ARRAY['designer-space', 'tea-house', 'lunch-only-public', 'minimalist'],
  false
),

-- YAKINIKU (12 restaurants)
-- 87. YORONIKU
(
  'YORONIKU', 'よろにく',
  'omotesando', 'Omotesando', '表参道',
  'yakiniku', 'Yakiniku', '焼肉',
  15000, 25000, 4, 4.5,
  'One of Tokyo''s most celebrated yakiniku, famous for grilled wagyu wrapped in bite-sized rice balls. The Truffle Sukiyaki is a must-try signature.',
  '東京を代表する焼肉店。肉をシャリに乗せて食べるスタイルの発祥。トリュフすき焼きは世界中の食通を魅了する看板メニュー。',
  'phone', 'Extremely hard to reserve. Try OMAKASE or Tabelog. Book 1-2 months ahead.',
  false, true, true,
  NULL, NULL, NULL, NULL, NULL,
  'Luna Rossa B1F, 6-6-22 Minamiaoyama, Minato-ku, Tokyo',
  '東京都港区南青山6-6-22 ルナロッサB1F',
  false, true,
  ARRAY['wagyu', 'premium', 'reservation-required', 'famous', 'counter-dining'],
  true
),
-- 88. Ushigoro S. Ginza
(
  'Ushigoro S. Ginza', 'うしごろS 銀座',
  'ginza', 'Ginza', '銀座',
  'yakiniku', 'Yakiniku', '焼肉',
  18000, 30000, 3, 4.5,
  'Flagship of the Ushigoro Group with all-private-room dining and a dedicated grilling chef per table. 32-month aged Japanese Black cattle.',
  'うしごろグループの最高級ブランド。全席個室で専属焼き師が最高級和牛を焼き上げる。鳥取県田村牧場の32ヶ月以上肥育黒毛和牛。',
  'online', 'Book via TableCheck or phone. Reservations 2-4 weeks ahead. All seats private rooms.',
  true, false, true,
  NULL, NULL, NULL, NULL, NULL,
  '6F GINZA 777 ADC Building, 7-7-7 Ginza, Chuo-ku, Tokyo',
  '東京都中央区銀座7-7-7 GINZA 777 ADCビル 6F',
  true, true,
  ARRAY['wagyu', 'premium', 'private-room', 'omakase', 'full-service-grilling'],
  true
),
-- 89. Yakiniku Jumbo Hanare
(
  'Yakiniku Jumbo Hanare', '焼肉ジャンボ はなれ',
  'kanda', 'Kanda', '神田',
  'yakiniku', 'Yakiniku', '焼肉',
  10000, 18000, 3, 4.4,
  'Perennial Tabelog Top 100 Yakiniku and Silver Award winner, specializing in A5 Kuroge Wagyu near Hongo-Sanchome station.',
  '食べログ焼肉百名店、シルバーアワード受賞の名店。本郷三丁目駅近くでA5黒毛和牛を堪能。',
  'phone', 'Call to reserve. Book at least 2 weeks ahead. Near Hongo-Sanchome Station.',
  false, true, false,
  NULL, NULL, NULL, NULL, NULL,
  'Anritsu Building, 3-27-9 Hongo, Bunkyo-ku, Tokyo',
  '東京都文京区本郷3-27-9 安里津ビル',
  false, true,
  ARRAY['wagyu', 'premium', 'tabelog-award', 'intimate'],
  true
),
-- 90. Yakiniku Kappo Note
(
  'Yakiniku Kappo Note', '焼肉割烹 ノ音',
  'azabu_juban', 'Azabu-Juban', '麻布十番',
  'yakiniku', 'Yakiniku', '焼肉',
  20000, 30000, 4, 4.6,
  'Intimate 8-seat omakase yakiniku blending kappo techniques with finest wagyu. About 20 dishes showcase extraordinary creativity.',
  'わずか8席の焼肉割烹。約20品のおまかせコースで最高級和牛の旨味を割烹の技法で引き出す。',
  'online', 'Reservation required. Book via OMAKASE. Only 8 seats. Book 1+ month ahead.',
  false, true, false,
  NULL, NULL, NULL, NULL, NULL,
  'Tougami Building 1F, 2-9-5 Azabujuban, Minato-ku, Tokyo',
  '東京都港区麻布十番2-9-5 東上ビル1F',
  false, true,
  ARRAY['wagyu', 'premium', 'omakase', 'kappo', 'counter-dining', 'intimate'],
  true
),
-- 91. Yakiniku Ushigoro Nishiazabu
(
  'Yakiniku Ushigoro Nishiazabu', '焼肉うしごろ 西麻布本店',
  'roppongi', 'Roppongi', '六本木',
  'yakiniku', 'Yakiniku', '焼肉',
  10000, 18000, 3, 4.3,
  'The original Ushigoro flagship serving strictly A5-rank wagyu in upscale Nishiazabu.',
  'うしごろブランドの原点。西麻布の落ち着いた雰囲気でA5ランクの和牛を堪能。',
  'online', 'Book via TableCheck or phone. Reserve 1-2 weeks ahead.',
  true, true, true,
  NULL, NULL, NULL, NULL, NULL,
  'Barbizon73 1F, 2-24-14 Nishiazabu, Minato-ku, Tokyo',
  '東京都港区西麻布2-24-14 バルビゾン73 1F',
  false, true,
  ARRAY['wagyu', 'premium', 'nishiazabu'],
  false
),
-- 92. Yakiniku Champion Ebisu
(
  'Yakiniku Champion Ebisu', '焼肉チャンピオン 恵比寿本店',
  'ebisu', 'Ebisu', '恵比寿',
  'yakiniku', 'Yakiniku', '焼肉',
  5000, 8000, 1, 4.0,
  'Beloved Ebisu institution with A5 wagyu at surprisingly affordable prices. Both familiar cuts and rare offal selections.',
  '恵比寿で愛される人気焼肉店。A5和牛を手頃な価格で楽しめ、定番から希少部位まで幅広い。',
  'online', 'Reservations recommended for dinner. Walk-ins possible.',
  true, true, false,
  NULL, NULL, NULL, NULL, NULL,
  'Amemiya Building, 1-2-8 Ebisu Minami, Shibuya-ku, Tokyo',
  '東京都渋谷区恵比寿南1-2-8 雨宮ビル',
  false, true,
  ARRAY['wagyu', 'casual', 'popular', 'rare-cuts'],
  false
),
-- 93. Yakiniku Toraji Ebisu
(
  'Yakiniku Toraji Ebisu', '焼肉トラジ 恵比寿庵店',
  'ebisu', 'Ebisu', '恵比寿',
  'yakiniku', 'Yakiniku', '焼肉',
  4000, 8000, 1, 3.9,
  'The original Toraji since 1995 with modern interior and semi-private rooms. Fresh, quality lean beef at mid-range prices.',
  '1995年創業のトラジ発祥の地。モダンな内装と半個室で新鮮な上質赤身肉を楽しめる。',
  'online', 'Easy to book online. Lunch sets are great value.',
  true, false, true,
  NULL, NULL, NULL, NULL, NULL,
  '1-1-10 Ebisu Minami, Shibuya-ku, Tokyo',
  '東京都渋谷区恵比寿南1-1-10',
  true, true,
  ARRAY['casual', 'semi-private', 'lunch-deals', 'family-friendly'],
  false
),
-- 94. Nikuya no Daidokoro Shinjuku
(
  'Nikuya no Daidokoro Shinjuku', '肉屋の台所 新宿店',
  'shinjuku', 'Shinjuku', '新宿',
  'yakiniku', 'Yakiniku', '焼肉',
  4500, 8000, 1, 3.8,
  'Popular all-you-can-eat wagyu yakiniku near Shinjuku Station. A4/A5 grade beef in 100-minute courses with QR code ordering and multilingual menus.',
  '新宿駅近くの和牛食べ放題焼肉店。A4・A5ランクの和牛を100分間堪能。多言語メニューとQRコード注文。',
  'online', 'Book online. QR code ordering with English menu. 100-minute time limit.',
  true, false, true,
  NULL, NULL, NULL, NULL, NULL,
  'Kabukicho, Shinjuku-ku, Tokyo',
  '東京都新宿区歌舞伎町',
  true, true,
  ARRAY['all-you-can-eat', 'wagyu', 'tourist-friendly', 'english-menu'],
  false
),
-- 95. Tokyo Yakiniku Heijoen Asakusa
(
  'Tokyo Yakiniku Heijoen Asakusa', '東京焼肉 平城苑 浅草総本店',
  'asakusa', 'Asakusa', '浅草',
  'yakiniku', 'Yakiniku', '焼肉',
  4000, 7000, 1, 3.9,
  'Established in 1970 with 50+ years of history. A5 wagyu in refined atmosphere near Sensoji temple at reasonable prices.',
  '1970年創業の老舗焼肉店。50年以上の歴史に裏打ちされた技術で浅草寺近くでA5和牛を手頃に提供。',
  'online', 'Easy to reserve online. Near Sensoji temple, great for combining with sightseeing.',
  true, false, true,
  NULL, NULL, NULL, NULL, NULL,
  'Asakusa, Taito-ku, Tokyo',
  '東京都台東区浅草',
  true, true,
  ARRAY['established', 'traditional', 'tourist-area', 'family-friendly'],
  false
),
-- 96. Yakiniku Ushigoro Ikebukuro
(
  'Yakiniku Ushigoro Ikebukuro', '焼肉うしごろ 池袋店',
  'ikebukuro', 'Ikebukuro', '池袋',
  'yakiniku', 'Yakiniku', '焼肉',
  5000, 8000, 1, 4.0,
  'Accessible branch of the renowned Ushigoro yakiniku brand. Same A5 wagyu quality in a casual atmosphere near Ikebukuro Station.',
  '名門うしごろブランドの池袋店。A5和牛へのこだわりはそのままにカジュアルな雰囲気で本格焼肉。',
  'online', 'Book via TableCheck or phone. More accessible than the premium S. branches.',
  true, true, true,
  NULL, NULL, NULL, NULL, NULL,
  'Near Ikebukuro Station, Toshima-ku, Tokyo',
  '東京都豊島区（池袋駅付近）',
  true, true,
  ARRAY['wagyu', 'casual', 'accessible'],
  false
),
-- 97. Yakiniku Dan Shinjuku
(
  'Yakiniku Dan Shinjuku', '焼肉 壇 新宿本店',
  'shinjuku', 'Shinjuku', '新宿',
  'yakiniku', 'Yakiniku', '焼肉',
  3000, 6000, 1, 3.8,
  'Popular casual yakiniku in Kabukicho with good quality wagyu at wallet-friendly prices. Lively atmosphere in the nightlife district.',
  '歌舞伎町エリアの人気カジュアル焼肉店。手頃な価格で和牛を楽しめ、新宿東口の賑やかな雰囲気が魅力。',
  'online', 'Walk-ins welcome but busy on weekends. Easy to find near Kabukicho.',
  true, true, false,
  NULL, NULL, NULL, NULL, NULL,
  'Kabukicho, Shinjuku-ku, Tokyo',
  '東京都新宿区歌舞伎町',
  false, true,
  ARRAY['casual', 'budget-friendly', 'nightlife-area'],
  false
),
-- 98. Yakiniku Rikimaru Ikebukuro
(
  'Yakiniku Rikimaru Ikebukuro', '焼肉りきまる 池袋東口店',
  'ikebukuro', 'Ikebukuro', '池袋',
  'yakiniku', 'Yakiniku', '焼肉',
  3000, 5000, 1, 3.7,
  'Affordable yakiniku near Ikebukuro East Exit with various set menus and a la carte options in a casual, energetic setting.',
  '池袋東口の手頃な焼肉店。リーズナブルながら質の良い焼肉を楽しめる。セットメニューも充実。',
  'online', 'Walk-ins welcome. Budget-friendly near Ikebukuro Station East Exit.',
  true, true, false,
  NULL, NULL, NULL, NULL, NULL,
  'FLC Building 5F, 1-22-2 Minamiikebukuro, Toshima-ku, Tokyo',
  '東京都豊島区南池袋1-22-2 FLCビル5F',
  true, true,
  ARRAY['budget-friendly', 'casual'],
  false
),

-- TONKATSU (8 restaurants)
-- 99. Tonkatsu Maisen Aoyama Honten
(
  'Tonkatsu Maisen Aoyama Honten', 'とんかつ まい泉 青山本店',
  'omotesando', 'Omotesando', '表参道',
  'tonkatsu', 'Tonkatsu', 'とんかつ',
  1500, 3000, 1, 4.1,
  'A Tokyo institution housed in a beautifully converted 1960s bathhouse near Omotesando. Juicy, tender pork cutlets with perfectly crispy coating.',
  '表参道駅近くの元銭湯を改装した空間で楽しむ老舗とんかつ。衣はサクサク、中はジューシー。',
  'walk-in', 'No reservations needed. Short wait during peak lunch. Look for the distinctive bathhouse building.',
  true, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '4-8-5 Jingumae, Shibuya-ku, Tokyo',
  '東京都渋谷区神宮前4-8-5',
  true, true,
  ARRAY['institution', 'famous', 'converted-bathhouse', 'tourist-friendly'],
  false
),
-- 100. Tonki Meguro Honten
(
  'Tonki Meguro Honten', 'とんき 目黒本店',
  'ebisu', 'Meguro', '目黒',
  'tonkatsu', 'Tonkatsu', 'とんかつ',
  1900, 2500, 1, 4.2,
  'A true Tokyo institution since 1939 with open-kitchen counter seating. Watch the perfectly choreographed tonkatsu operation. Simple menu focused on basics.',
  '1939年創業の老舗。カウンター越しに職人技を見ながら食べるとんかつは格別。シンプルなメニューで基本を極めた。',
  'walk-in', 'No reservations. Counter only. 1 min from Meguro Station. Closed Tuesdays. Opens at 4pm.',
  false, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '1-1-2 Shimomeguro, Meguro-ku, Tokyo',
  '東京都目黒区下目黒1-1-2',
  false, true,
  ARRAY['institution', 'since-1939', 'counter-only', 'open-kitchen'],
  false
),
-- 101. Tonkatsu Marugo
(
  'Tonkatsu Marugo', 'とんかつ 丸五',
  'akihabara', 'Akihabara', '秋葉原',
  'tonkatsu', 'Tonkatsu', 'とんかつ',
  1800, 3000, 2, 4.3,
  'One of the rare Michelin-starred tonkatsu spots. Unique low-temperature, slow-frying technique perfected over 40 years for exceptionally juicy cutlets.',
  'ミシュラン星獲得経験を持つ名店。40年以上かけて磨き上げた低温揚げ技法による格別にジューシーなとんかつ。',
  'walk-in', 'No reservations. Always a queue — arrive before opening. 5 min from Akihabara Station.',
  false, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '1-8-14 Sotokanda, Chiyoda-ku, Tokyo',
  '東京都千代田区外神田1-8-14',
  true, true,
  ARRAY['michelin', 'famous', 'long-queue', 'low-temp-frying'],
  false
),
-- 102. Ponta Honke
(
  'Ponta Honke', 'ぽん多本家',
  'ueno', 'Ueno', '上野',
  'tonkatsu', 'Tonkatsu', 'とんかつ',
  2000, 4000, 2, 4.2,
  'Established in 1905, widely hailed as the birthplace of modern tonkatsu. Fourth generation. Michelin Bib Gourmand. Cash only.',
  '1905年創業、とんかつ発祥の店。4代目が受け継ぐ100年以上の技法。ミシュランビブグルマン選出。',
  'walk-in', 'No reservations. Closed Mondays. Cash only.',
  false, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '3-23-3 Ueno, Taito-ku, Tokyo',
  '東京都台東区上野3-23-3',
  true, true,
  ARRAY['birthplace-of-tonkatsu', 'since-1905', 'michelin-bib-gourmand', 'historic'],
  false
),
-- 103. Butagumi
(
  'Butagumi', '豚組',
  'roppongi', 'Nishi-Azabu', '西麻布',
  'tonkatsu', 'Tonkatsu', 'とんかつ',
  2000, 4000, 2, 4.1,
  'Owner sampled over 150 Japanese pork brands to select the very best. Elevates tonkatsu to fine-dining levels with heritage pork.',
  'オーナーが150種以上の銘柄豚を食べ比べて厳選。西麻布の洗練された空間でとんかつを極上の料理に昇華。',
  'online', 'Reservations recommended. Closed Mondays. Near Nogizaka Station exit 5.',
  false, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '2-24-9 Nishi-Azabu, Minato-ku, Tokyo',
  '東京都港区西麻布2-24-9',
  true, true,
  ARRAY['heritage-pork', 'premium-pork', 'nishi-azabu'],
  false
),
-- 104. Tonkatsu Aoki Ginza
(
  'Tonkatsu Aoki Ginza', 'とんかつ檍 銀座店',
  'ginza', 'Ginza', '銀座',
  'tonkatsu', 'Tonkatsu', 'とんかつ',
  1500, 2500, 1, 4.0,
  'Tabelog Top 100-listed tonkatsu in Ginza. Premium-grade pork with perfectly golden, crispy crust and juicy interior.',
  '食べログ百名店に選出された銀座のとんかつ専門店。黄金色のサクサク衣とジューシーな中身が評判。',
  'walk-in', 'No reservations. Short walk from JR Shimbashi Station.',
  false, true, false,
  NULL, NULL, NULL, NULL, NULL,
  'B1F 3rd Soiree de Building, 8-8-7 Ginza, Chuo-ku, Tokyo',
  '東京都中央区銀座8-8-7 第3ソワレ・ドビル B1F',
  true, true,
  ARRAY['tabelog-top100', 'ginza', 'expert-technique'],
  false
),
-- 105. Tonkatsu Nanaido
(
  'Tonkatsu Nanaido', 'とんかつ七井戸',
  'omotesando', 'Jingumae', '神宮前',
  'tonkatsu', 'Tonkatsu', 'とんかつ',
  2000, 3500, 2, 4.1,
  'Michelin-recognized tonkatsu gently fried in lard at low temperature for a golden crispy panko with tender, juicy pork inside.',
  'ミシュラン掲載のとんかつ店。ラードで低温じっくり揚げることで黄金色のパン粉衣はサクサク、中はしっとり。',
  'walk-in', 'No reservations. About 5 min from Gaienmae Station. Small shop, expect a wait.',
  false, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '104 Rosa Bianca, 3-42-11 Jingumae, Shibuya-ku, Tokyo',
  '東京都渋谷区神宮前3-42-11 ローザビアンカ104',
  true, true,
  ARRAY['michelin', 'low-temp-frying', 'lard-fried'],
  false
),
-- 106. Tonkatsu Hasegawa Higashiginza
(
  'Tonkatsu Hasegawa Higashiginza', 'とんかつ はせ川 東銀座店',
  'tsukiji', 'Higashi-Ginza', '東銀座',
  'tonkatsu', 'Tonkatsu', 'とんかつ',
  1500, 3000, 2, 4.1,
  'Michelin Bib Gourmand tonkatsu with thick, perfectly fried cutlets and delicate crunchy panko coating.',
  'ミシュランビブグルマン獲得のとんかつ店。厳選豚肉に繊細なパン粉衣の分厚く完璧なカツ。',
  'walk-in', 'No reservations needed. Convenient near Tsukiji area.',
  false, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '1F Takahashi Building, 1-13-11 Tsukiji, Chuo-ku, Tokyo',
  '東京都中央区築地1-13-11 高橋ビル1F',
  true, true,
  ARRAY['michelin-bib-gourmand', 'tsukiji-area', 'thick-cut'],
  false
),

-- UDON & SOBA (12 restaurants)
-- 107. Udon Shin
(
  'Udon Shin', 'うどん 慎',
  'shinjuku', 'Yoyogi', '代々木',
  'udon_soba', 'Udon & Soba', 'うどん・蕎麦',
  1000, 2000, 2, 4.4,
  'Michelin-featured udon with just 6 counter seats. Handmade noodles aged overnight for optimal chewy texture. Ticketing system from 9am.',
  'ミシュラン掲載のうどん店。カウンター6席の小さな店で一晩寝かせた手打ち麺のもちもち食感が絶品。整理券制。',
  'walk-in', 'Ticket system — go from 9am for a numbered ticket. 5 min from Yoyogi Station.',
  false, true, false,
  NULL, NULL, NULL, NULL, NULL,
  'Soma Building 1F, 2-20-16 Yoyogi, Shibuya-ku, Tokyo',
  '東京都渋谷区代々木2-20-16 相馬ビル1F',
  true, true,
  ARRAY['michelin', 'handmade', 'udon', 'ticket-system'],
  false
),
-- 108. Udon Maruka
(
  'Udon Maruka', 'うどん丸香',
  'kanda', 'Jimbocho', '神保町',
  'udon_soba', 'Udon & Soba', 'うどん・蕎麦',
  800, 1500, 1, 4.3,
  'Best Sanuki-style udon outside Kagawa Prefecture. Thick, chewy handmade noodles draw 45+ minute queues.',
  '本場讃岐のうどん名店で修行した店主が営む。もちもちの手打ち麺に45分以上の行列ができる。',
  'walk-in', 'No reservations. Expect 30-45 min wait. 4 min from Jimbocho Station. Closed Sunday.',
  false, true, false,
  NULL, NULL, NULL, NULL, NULL,
  'NEW SURUGADAI Bld 1F, 3-16-1 Kanda Ogawamachi, Chiyoda-ku, Tokyo',
  '東京都千代田区神田小川町3-16-1 ニュー駿河台ビル1F',
  true, true,
  ARRAY['sanuki-udon', 'udon', 'handmade', 'long-queue', 'affordable'],
  false
),
-- 109. Kanda Matsuya
(
  'Kanda Matsuya', '神田まつや',
  'kanda', 'Kanda', '神田',
  'udon_soba', 'Udon & Soba', 'うどん・蕎麦',
  800, 1800, 1, 4.1,
  'Operating since 1884 in a government-designated historic wooden building. Handmade buckwheat noodles showcasing pure soba flavor.',
  '1884年創業、東京都指定歴史的建造物の木造店舗。全国から厳選したそば粉で手打ちする蕎麦。もりそばが名物。',
  'walk-in', 'No reservations. 1 min from Ogawamachi/Awajicho Station. Historic wooden building.',
  false, false, false,
  NULL, NULL, NULL, NULL, NULL,
  '1-13 Kanda Sudacho, Chiyoda-ku, Tokyo',
  '東京都千代田区神田須田町1-13',
  true, true,
  ARRAY['soba', 'since-1884', 'historic-building', 'handmade', 'traditional'],
  false
),
-- 110. Sarashina Horii
(
  'Sarashina Horii', '総本家 更科堀井',
  'azabu_juban', 'Azabu-Juban', '麻布十番',
  'udon_soba', 'Udon & Soba', 'うどん・蕎麦',
  1200, 3000, 1, 4.2,
  'Established in 1789, this 230+ year-old soba institution is famous for distinctive white Sarashina soba from the heart of the buckwheat grain.',
  '1789年創業、230年以上の歴史を誇る蕎麦の名門。そばの実の芯だけを使った白い更科蕎麦が名物。',
  'walk-in', 'No reservations needed. 5-7 min from Azabu-Juban Station.',
  false, false, true,
  NULL, NULL, 'https://www.sarashina-horii.com/en/', NULL, NULL,
  '3-11-4 Motoazabu, Minato-ku, Tokyo',
  '東京都港区元麻布3-11-4',
  true, true,
  ARRAY['soba', 'since-1789', 'sarashina-soba', 'white-soba', 'historic'],
  false
),
-- 111. Honmura An
(
  'Honmura An', '本むら庵',
  'roppongi', 'Roppongi', '六本木',
  'udon_soba', 'Udon & Soba', 'うどん・蕎麦',
  1500, 3000, 1, 4.2,
  'Some of the best soba in Tokyo. Famous uni (sea urchin) soba draws diners from around the world.',
  '東京最高峰の蕎麦店の一つ。ウニ蕎麦は世界中の食通が訪れる名物メニュー。',
  'phone', 'Reservations recommended for dinner. Closed Mondays. Try the uni soba.',
  true, false, true,
  NULL, NULL, NULL, NULL, NULL,
  '2F, 7-14-18 Roppongi, Minato-ku, Tokyo',
  '東京都港区六本木7-14-18 2F',
  true, true,
  ARRAY['soba', 'uni-soba', 'refined', 'roppongi'],
  false
),
-- 112. Tamawarai
(
  'Tamawarai', '玉笑',
  'omotesando', 'Jingumae', '神宮前',
  'udon_soba', 'Udon & Soba', 'うどん・蕎麦',
  1500, 3000, 2, 4.5,
  'Michelin one-star soba from 2016-2026, hidden in quiet Harajuku. Chef grinds buckwheat from his own garden. Expect 1-2 hour wait.',
  '2016年から連続ミシュラン一つ星獲得の蕎麦の名店。原宿の裏通りに佇み、自家栽培のそば粉を自ら挽いて打つ。',
  'walk-in', 'No reservations. 1-2 hour wait. Only 14 seats. Near Omotesando.',
  false, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '5-23-3 Jingumae, Shibuya-ku, Tokyo',
  '東京都渋谷区神宮前5-23-3',
  true, true,
  ARRAY['soba', 'michelin-star', 'handmade', 'self-grown-buckwheat'],
  false
),
-- 113. Asakusa Hirayama
(
  'Asakusa Hirayama', '浅草 平山',
  'asakusa', 'Asakusa', '浅草',
  'udon_soba', 'Udon & Soba', 'うどん・蕎麦',
  1200, 2500, 1, 4.3,
  'Three-consecutive-year Michelin Bib Gourmand winner. 100% buckwheat juwari soba with homemade flour. Tempura fried to specialty-shop standards.',
  'ミシュランビブグルマンを3年連続受賞。自家製粉した十割蕎麦は風味豊か。天ぷらも専門店レベル。',
  'phone', 'Reservations recommended. 2 min from Tawaramachi Station. Can sell out early.',
  false, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '1-3-14 Nishiasakusa, Taito-ku, Tokyo',
  '東京都台東区西浅草1-3-14',
  true, true,
  ARRAY['soba', 'michelin-bib-gourmand', 'juwari-soba', 'tempura'],
  false
),
-- 114. Handmade Udon Ieyasu Asakusa
(
  'Handmade Udon Ieyasu Asakusa', '手打ちうどん いえやす 浅草店',
  'asakusa', 'Asakusa', '浅草',
  'udon_soba', 'Udon & Soba', 'うどん・蕎麦',
  800, 1500, 1, 3.8,
  'Popular handmade udon in Asakusa''s tourist district with thick chewy noodles. Convenient near Sensoji temple for sightseeing lunch.',
  '浅草の観光エリアにある手打ちうどん店。太くてもちもちの麺を温冷さまざまに楽しめる。浅草寺観光の合間に。',
  'walk-in', 'Walk-ins only. Near Sensoji. Affordable and filling.',
  true, true, false,
  NULL, NULL, NULL, NULL, NULL,
  'Asakusa, Taito-ku, Tokyo',
  '東京都台東区浅草',
  true, true,
  ARRAY['udon', 'handmade', 'tourist-area', 'affordable'],
  false
),
-- 115. Monju
(
  'Monju', '文殊',
  'asakusa', 'Asakusa', '浅草',
  'udon_soba', 'Udon & Soba', 'うどん・蕎麦',
  800, 1200, 1, 3.7,
  'Classic standing soba in the Asakusa underground arcade. Freshly boiled noodles with gentle bonito-dashi from just 380 yen.',
  '浅草地下街にある立ち食い蕎麦の名店。注文ごとに茹でる蕎麦と優しい鰹出汁。380円から楽しめる。',
  'walk-in', 'No reservation needed. Underground arcade from metro station. Standing only, very fast.',
  false, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '1-1-12 Asakusa, Taito-ku, Tokyo (underground arcade)',
  '東京都台東区浅草1-1-12 浅草地下街',
  true, true,
  ARRAY['soba', 'standing-soba', 'ultra-affordable'],
  false
),
-- 116. Nagasaka Sarashina Honten
(
  'Nagasaka Sarashina Honten', '麻布永坂 更科本店',
  'azabu_juban', 'Azabu-Juban', '麻布十番',
  'udon_soba', 'Udon & Soba', 'うどん・蕎麦',
  1000, 2500, 1, 4.0,
  'Another historic sarashina soba lineage dating to 1789. Pure white soba from buckwheat grain cores with subtly sweet, delicate flavor.',
  '1789年に遡る更科蕎麦の名店。そばの実の芯から挽いた純白の蕎麦はほのかな甘みと繊細な風味。',
  'walk-in', 'Walk-ins welcome. In the same neighborhood as Sarashina Horii.',
  false, false, true,
  NULL, NULL, NULL, NULL, NULL,
  '3-11-4 Azabujuban, Minato-ku, Tokyo',
  '東京都港区麻布十番3-11-4',
  true, true,
  ARRAY['soba', 'sarashina-soba', 'since-1789', 'white-soba', 'historic'],
  false
),
-- 117. Kineya Mugimaru Asakusa
(
  'Kineya Mugimaru Asakusa', '杵屋麦丸 浅草店',
  'asakusa', 'Asakusa', '浅草',
  'udon_soba', 'Udon & Soba', 'うどん・蕎麦',
  800, 1500, 1, 3.6,
  'Halal-certified handmade udon near Tsukuba Express Asakusa Station. Curry udon, beef udon, and vegetarian options from 455 yen.',
  'つくばエクスプレス浅草駅近くのハラール対応手打ちうどん店。カレーうどんや肉うどん、ベジタリアン向けも。',
  'walk-in', 'Walk-in only. Halal certified — rare for udon shops. Very affordable.',
  true, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '2-11-4 Asakusa, Taito-ku, Tokyo',
  '東京都台東区浅草2-11-4',
  true, true,
  ARRAY['udon', 'halal', 'handmade', 'affordable', 'vegetarian-options'],
  false
),
-- 118. Sobadokoro Kameya
(
  'Sobadokoro Kameya', 'そば処 かめや',
  'ueno', 'Okachimachi', '御徒町',
  'udon_soba', 'Udon & Soba', 'うどん・蕎麦',
  800, 1200, 1, 3.8,
  'Beloved 50+ year standing soba near Ueno''s Ameyoko. Quick, affordable, authentic — the tempura soba is the crowd favorite.',
  '上野アメ横近くで50年以上愛される立ち食い蕎麦の名店。早い・安い・旨いの三拍子。天ぷらそばが一番人気。',
  'walk-in', 'Walk-in only. Standing soba near Ameyoko market. Very quick service.',
  false, true, false,
  NULL, NULL, NULL, NULL, NULL,
  'Near Okachimachi Station, Taito-ku, Tokyo',
  '東京都台東区（御徒町駅・アメ横付近）',
  true, true,
  ARRAY['soba', 'standing-soba', 'ameyoko', '50-years', 'quick'],
  false
),

-- CURRY (8 restaurants)
-- 119. Bondy Jimbocho Honten
(
  'Bondy Jimbocho Honten', 'ボンディ 神保町本店',
  'kanda', 'Jimbocho', '神保町',
  'curry', 'Curry', 'カレー',
  1200, 2000, 1, 4.1,
  'Champion of the first Kanda Curry Grand Prix. 50+ year European-style curry hidden above a bookstore. Deep brown roux with secret spices and fruits.',
  '第1回神田カレーグランプリ優勝店。50年以上の歴史を持つ欧風カレーの名店。秘伝のスパイスとフルーツのルー。',
  'walk-in', 'No reservations. 2nd floor above a bookstore in Jimbocho. Queues at lunch.',
  false, false, false,
  NULL, NULL, NULL, NULL, NULL,
  '2F Kanda Kosho Center, 2-3 Kanda-Jimbocho, Chiyoda-ku, Tokyo',
  '東京都千代田区神田神保町2-3 神田古書センター2F',
  true, true,
  ARRAY['european-curry', 'japanese-curry', 'jimbocho', 'institution'],
  false
),
-- 120. Delhi Ueno
(
  'Delhi Ueno', 'デリー 上野店',
  'ueno', 'Ueno', '上野',
  'curry', 'Curry', 'カレー',
  1000, 1800, 1, 4.0,
  'Established in 1956, the cradle of Japanese-style Indian curry. The Kashmir Curry is legendarily spicy. Cash only.',
  '1956年創業、日本式インドカレーの元祖。カシミールカレーの辛さは伝説的。現金のみ。',
  'walk-in', 'No reservations. Long lines at lunch. 2 min from Ueno-Hirokoji Station. Cash only.',
  false, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '3-42-2 Yushima, Bunkyo-ku, Tokyo',
  '東京都文京区湯島3-42-2',
  true, true,
  ARRAY['indian-curry', 'since-1956', 'spicy', 'kashmir-curry', 'historic'],
  false
),
-- 121. Magic Spice Shimokitazawa
(
  'Magic Spice Shimokitazawa', 'マジックスパイス 下北沢店',
  'shimokitazawa', 'Shimokitazawa', '下北沢',
  'curry', 'Curry', 'カレー',
  1200, 2000, 1, 3.9,
  'The legendary inventor of soup curry. Choose from 7 spice levels with mystical names like Nirvana, Paradise, and Void.',
  'スープカレーの元祖として名高い伝説の店。涅槃・極楽・虚空など7段階の辛さレベルから選べる。',
  'walk-in', 'No reservations. 4 min from Shimokitazawa Station. Check schedule for open days.',
  false, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '2-30-14 Daizawa, Setagaya-ku, Tokyo',
  '東京都世田谷区代沢2-30-14',
  true, true,
  ARRAY['soup-curry', 'inventor', 'spicy', 'shimokitazawa'],
  false
),
-- 122. Spice Post
(
  'Spice Post', 'スパイスポスト',
  'shibuya', 'Yoyogi-Hachiman', '代々木八幡',
  'curry', 'Curry', 'カレー',
  1200, 2000, 2, 4.2,
  'Tabelog Top 100 curry with only 6 counter seats. Creative spice curry sold out daily. The SPECIAL Combo is a must-try.',
  '食べログカレー百名店。カウンター6席で毎日売り切れ次第終了。レバノンキーマなど独創的なスパイスカレー。',
  'walk-in', 'No reservations. Opens 10:30 weekdays, 9:00 weekends. Sells out daily. Cash only.',
  false, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '1-52-2 Tomigaya, Shibuya-ku, Tokyo',
  '東京都渋谷区富ヶ谷1-52-2',
  true, false,
  ARRAY['spice-curry', 'tabelog-top100', 'sells-out', 'counter-only', 'creative'],
  false
),
-- 123. Moyan Curry Shinjuku
(
  'Moyan Curry Shinjuku', 'もうやんカレー 新宿東口店',
  'shinjuku', 'Shinjuku', '新宿',
  'curry', 'Curry', 'カレー',
  800, 1500, 1, 3.8,
  'Unique curry fusion since 1997 using 25 spices with Japanese, Chinese, Indian, Nepalese influences. Lunch buffet is exceptional value. Gluten-free.',
  '1997年創業。25種のスパイスで多国籍の要素を融合させた独自のカレー。ランチビュッフェがお得。グルテンフリー。',
  'walk-in', 'No reservations needed. Lunch buffet is the best deal. Gluten-free friendly.',
  true, false, false,
  NULL, NULL, NULL, NULL, NULL,
  'Cherry Building 1F, 1-12-5 Kabukicho, Shinjuku-ku, Tokyo',
  '東京都新宿区歌舞伎町1-12-5 チェリービル1F',
  true, true,
  ARRAY['japanese-curry', 'fusion', 'gluten-free', 'buffet', 'affordable'],
  false
),
-- 124. Japanese Spice Curry wacca
(
  'Japanese Spice Curry wacca', 'ジャパニーズスパイスカリー ワッカ',
  'ginza', 'Hatchobori', '八丁堀',
  'curry', 'Curry', 'カレー',
  1000, 1800, 2, 4.1,
  'Grand Prix winner of Creative Spice Curry category. Osaka transplant fusing Japanese ingredients with Indian spices. Each plate is colorful art.',
  'クリエイティブスパイスカレー部門グランプリ受賞の大阪発店。和の食材とインドスパイスを融合させた彩り鮮やかなプレート。',
  'walk-in', 'No reservations. Small shop, sells out. Near Hatchobori Station.',
  false, true, false,
  NULL, NULL, NULL, NULL, NULL,
  'Shoji Building 1F, 2-19-7 Hatchobori, Chuo-ku, Tokyo',
  '東京都中央区八丁堀2-19-7 庄司ビル1F',
  true, false,
  ARRAY['spice-curry', 'creative', 'award-winning', 'japanese-fusion'],
  false
),
-- 125. Curry Spice Gelateria Kalpasi
(
  'Curry Spice Gelateria Kalpasi', 'カレースパイスジェラテリア カルパシ',
  'shimokitazawa', 'Shimokitazawa', '下北沢',
  'curry', 'Curry', 'カレー',
  1000, 1800, 1, 4.0,
  'Unique Shimokitazawa spot combining South Indian-inspired spice curry with artisanal gelato. Creative dual concept.',
  '南インド系スパイスカレーと手作りジェラートを融合させた下北沢のユニークな店。',
  'walk-in', 'No reservations. Near Shimokitazawa Station. Try the curry AND gelato combo.',
  false, true, false,
  NULL, NULL, NULL, NULL, NULL,
  'Shimokitazawa, Setagaya-ku, Tokyo',
  '東京都世田谷区北沢',
  true, true,
  ARRAY['spice-curry', 'gelato', 'south-indian', 'shimokitazawa', 'creative'],
  false
),
-- 126. Nan Station
(
  'Nan Station', 'ナンステーション',
  'shimokitazawa', 'Shimokitazawa', '下北沢',
  'curry', 'Curry', 'カレー',
  800, 1500, 1, 3.7,
  'Authentic Nepalese-Indian curry with extra-large chewy naan at incredibly affordable prices. Lunch sets from just 500 yen.',
  '巨大でもちもちのナンと本格ネパール・インドカレー。ランチ500円からの驚きの価格。',
  'walk-in', 'No reservations needed. 5 min from Shimokitazawa North Exit. 500 yen lunch.',
  true, false, false,
  NULL, NULL, NULL, NULL, NULL,
  '1F Shimokitazawa City House 2, 3-23-23 Kitazawa, Setagaya-ku, Tokyo',
  '東京都世田谷区北沢3-23-23 下北沢シティハウス2 1F',
  true, true,
  ARRAY['indian-curry', 'nepalese', 'naan', 'ultra-affordable'],
  false
),

-- CAFE (8 restaurants)
-- 127. Chatei Hatou
(
  'Chatei Hatou', '茶亭 羽當',
  'shibuya', 'Shibuya', '渋谷',
  'cafe', 'Cafe', 'カフェ',
  800, 1500, 1, 4.3,
  'Tabelog Top 100 kissaten since 1989, said to have inspired Blue Bottle Coffee''s founder. Each cup hand-dripped in carefully selected antique cups.',
  '1989年開業、食べログ喫茶百名店。ブルーボトルコーヒー創業者にも影響を与えた名店。アンティークカップでハンドドリップ。',
  'walk-in', 'No reservations. 3 min from Shibuya East Exit. Hidden in an alley.',
  false, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '1F, 1-15-19 Shibuya, Shibuya-ku, Tokyo',
  '東京都渋谷区渋谷1-15-19 1F',
  true, true,
  ARRAY['kissaten', 'hand-drip', 'tabelog-top100', 'antique-cups'],
  false
),
-- 128. Cafe de l''Ambre
(
  'Cafe de l''Ambre', 'カフェ・ド・ランブル',
  'ginza', 'Ginza', '銀座',
  'cafe', 'Cafe', 'カフェ',
  700, 1500, 1, 4.2,
  'Tokyo''s legendary coffee-only kissaten since 1948. Nearly 30 single-origin varieties including aged beans from the 1950s. Coffee only — no food.',
  '1948年創業、コーヒーのみを提供する伝説の喫茶店。1950年代のエイジドビーンズを含む約30種のシングルオリジン。',
  'walk-in', 'No reservations. Coffee only — no food menu. Near Ginza Station.',
  false, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '8-10-15 Ginza, Chuo-ku, Tokyo',
  '東京都中央区銀座8-10-15',
  true, true,
  ARRAY['kissaten', 'since-1948', 'coffee-only', 'aged-beans', 'legendary'],
  false
),
-- 129. Kayaba Coffee
(
  'Kayaba Coffee', 'カヤバ珈琲',
  'ueno', 'Yanaka', '谷中',
  'cafe', 'Cafe', 'カフェ',
  500, 1200, 1, 4.0,
  'A 100-year-old kissaten in a 1916 machiya-style building in charming Yanaka. Famous for thick egg sandwich and Russian Coffee.',
  '1916年築の町家建築で100年以上の歴史を持つ谷中の喫茶店。名物の厚焼き玉子サンドとロシアンコーヒー。',
  'walk-in', 'No reservations. 10 min from Nippori Station through Yanaka Cemetery.',
  false, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '6-1-29 Yanaka, Taito-ku, Tokyo',
  '東京都台東区谷中6-1-29',
  true, false,
  ARRAY['kissaten', 'machiya', '100-years', 'yanaka', 'egg-sandwich', 'historic'],
  false
),
-- 130. Tajimaya Coffee
(
  'Tajimaya Coffee', '但馬屋珈琲店 本店',
  'shinjuku', 'Shinjuku', '新宿',
  'cafe', 'Cafe', 'カフェ',
  600, 1200, 1, 3.9,
  'Established in 1964 in Shinjuku''s Omoide Yokocho. Hand-sorts beans six times a week, roasts in-house, hand-drips through cloth filters.',
  '1964年、新宿思い出横丁に創業。週6回ハンドピックした豆を自家焙煎し、ネルドリップで一杯ずつ抽出。',
  'walk-in', 'No reservations. Inside Omoide Yokocho near Shinjuku West Exit. Open until 11pm.',
  false, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '1-2-6 Nishishinjuku, Shinjuku-ku, Tokyo',
  '東京都新宿区西新宿1-2-6',
  true, true,
  ARRAY['kissaten', 'omoide-yokocho', 'hand-roasted', 'nel-drip', 'since-1964'],
  false
),
-- 131. Saboru
(
  'Saboru', 'さぼうる',
  'kanda', 'Jimbocho', '神保町',
  'cafe', 'Cafe', 'カフェ',
  500, 1200, 1, 3.8,
  'Iconic Jimbocho kissaten since 1955 with eccentric tiki-inspired interior and decades of graffiti. Famous for rainbow cream sodas in 7 colors.',
  '1955年創業、神保町の名物喫茶店。ティキ風の内装に何十年分の落書き。7色のクリームソーダが名物。',
  'walk-in', 'No reservations. 30 seconds from Jimbocho Station A7. Closed Sundays.',
  false, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '1-11 Kanda-Jimbocho, Chiyoda-ku, Tokyo',
  '東京都千代田区神田神保町1-11',
  true, true,
  ARRAY['kissaten', 'since-1955', 'tiki-interior', 'cream-soda', 'jimbocho'],
  false
),
-- 132. Fuglen Tokyo
(
  'Fuglen Tokyo', 'フグレン トウキョウ',
  'shibuya', 'Tomigaya', '富ヶ谷',
  'cafe', 'Cafe', 'カフェ',
  500, 1500, 1, 4.1,
  'First overseas location of Oslo''s Fuglen since 2012. Light-roasted Norwegian-style coffee near Yoyogi Park. Cocktail bar at night.',
  'オスロの人気店フグレンの海外1号店。代々木公園近くで北欧スタイルの浅煎りコーヒー。夜はカクテルバーに。',
  'walk-in', 'No reservations. Near Yoyogi Park. Cafe by day, cocktail bar by night.',
  true, true, false,
  NULL, NULL, NULL, NULL, NULL,
  '1-16-11 Tomigaya, Shibuya-ku, Tokyo',
  '東京都渋谷区富ヶ谷1-16-11',
  true, true,
  ARRAY['specialty-coffee', 'norwegian', 'yoyogi-park', 'cocktail-bar'],
  false
),
-- 133. Coffee Seibu
(
  'Coffee Seibu', '珈琲西武',
  'shinjuku', 'Shinjuku', '新宿',
  'cafe', 'Cafe', 'カフェ',
  700, 1500, 1, 3.8,
  'One of Shinjuku''s most famous kissaten since 1964. Two floors with stunning stained-glass ceiling. Beloved for towering parfaits and fluffy pancakes.',
  '1964年創業、新宿を代表する喫茶店。ステンドグラス天井の2フロア店内でパフェとパンケーキが人気。',
  'walk-in', 'No reservations. 3 min from Shinjuku Station near Lumine Est.',
  false, false, false,
  NULL, NULL, NULL, NULL, NULL,
  '2F Metro Kaikan, 3-34-9 Shinjuku, Shinjuku-ku, Tokyo',
  '東京都新宿区新宿3-34-9 メトロ会館2F',
  true, true,
  ARRAY['kissaten', 'since-1964', 'stained-glass', 'parfait', 'pancakes', 'showa-retro'],
  false
),
-- 134. Kissaten Oujo
(
  'Kissaten Oujo', '喫茶 王城',
  'ueno', 'Ueno', '上野',
  'cafe', 'Cafe', 'カフェ',
  600, 1200, 1, 3.7,
  'Founded in 1975, this Ueno kissaten is a time capsule with chandeliers, marble tables, and classic furnishings. Peaceful retreat from Ameyoko.',
  '1975年創業の上野の名喫茶。シャンデリア、大理石のテーブル、クラシックな調度品のレトロ空間。',
  'walk-in', 'No reservations. Near Ueno Station. Peaceful retreat from Ameyoko.',
  false, false, false,
  NULL, NULL, NULL, NULL, NULL,
  'Near Ueno Station, Taito-ku, Tokyo',
  '東京都台東区（上野駅付近）',
  true, true,
  ARRAY['kissaten', 'since-1975', 'chandeliers', 'marble', 'retro-luxury', 'ueno'],
  false
)
;

-- ============================================
-- IZAKAYA section will be added after research
-- ============================================
